// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SigningKeyshareSecretsColumns holds the columns for the "signing_keyshare_secrets" table.
	SigningKeyshareSecretsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "signing_keyshare_id", Type: field.TypeUUID},
		{Name: "version", Type: field.TypeInt32},
		{Name: "secret_share", Type: field.TypeBytes},
	}
	// SigningKeyshareSecretsTable holds the schema information for the "signing_keyshare_secrets" table.
	SigningKeyshareSecretsTable = &schema.Table{
		Name:       "signing_keyshare_secrets",
		Columns:    SigningKeyshareSecretsColumns,
		PrimaryKey: []*schema.Column{SigningKeyshareSecretsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "signingkeysharesecret_signing_keyshare_id_version",
				Unique:  true,
				Columns: []*schema.Column{SigningKeyshareSecretsColumns[3], SigningKeyshareSecretsColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SigningKeyshareSecretsTable,
	}
)

func init() {
}
