// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/depositaddress"
	"github.com/lightsparkdev/spark/so/ent/depositaddresspartner"
	"github.com/lightsparkdev/spark/so/ent/partner"
)

// DepositAddressPartnerCreate is the builder for creating a DepositAddressPartner entity.
type DepositAddressPartnerCreate struct {
	config
	mutation *DepositAddressPartnerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (dapc *DepositAddressPartnerCreate) SetCreateTime(t time.Time) *DepositAddressPartnerCreate {
	dapc.mutation.SetCreateTime(t)
	return dapc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (dapc *DepositAddressPartnerCreate) SetNillableCreateTime(t *time.Time) *DepositAddressPartnerCreate {
	if t != nil {
		dapc.SetCreateTime(*t)
	}
	return dapc
}

// SetUpdateTime sets the "update_time" field.
func (dapc *DepositAddressPartnerCreate) SetUpdateTime(t time.Time) *DepositAddressPartnerCreate {
	dapc.mutation.SetUpdateTime(t)
	return dapc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (dapc *DepositAddressPartnerCreate) SetNillableUpdateTime(t *time.Time) *DepositAddressPartnerCreate {
	if t != nil {
		dapc.SetUpdateTime(*t)
	}
	return dapc
}

// SetID sets the "id" field.
func (dapc *DepositAddressPartnerCreate) SetID(u uuid.UUID) *DepositAddressPartnerCreate {
	dapc.mutation.SetID(u)
	return dapc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dapc *DepositAddressPartnerCreate) SetNillableID(u *uuid.UUID) *DepositAddressPartnerCreate {
	if u != nil {
		dapc.SetID(*u)
	}
	return dapc
}

// SetPartnerID sets the "partner" edge to the Partner entity by ID.
func (dapc *DepositAddressPartnerCreate) SetPartnerID(id uuid.UUID) *DepositAddressPartnerCreate {
	dapc.mutation.SetPartnerID(id)
	return dapc
}

// SetPartner sets the "partner" edge to the Partner entity.
func (dapc *DepositAddressPartnerCreate) SetPartner(p *Partner) *DepositAddressPartnerCreate {
	return dapc.SetPartnerID(p.ID)
}

// SetDepositAddressID sets the "deposit_address" edge to the DepositAddress entity by ID.
func (dapc *DepositAddressPartnerCreate) SetDepositAddressID(id uuid.UUID) *DepositAddressPartnerCreate {
	dapc.mutation.SetDepositAddressID(id)
	return dapc
}

// SetDepositAddress sets the "deposit_address" edge to the DepositAddress entity.
func (dapc *DepositAddressPartnerCreate) SetDepositAddress(d *DepositAddress) *DepositAddressPartnerCreate {
	return dapc.SetDepositAddressID(d.ID)
}

// Mutation returns the DepositAddressPartnerMutation object of the builder.
func (dapc *DepositAddressPartnerCreate) Mutation() *DepositAddressPartnerMutation {
	return dapc.mutation
}

// Save creates the DepositAddressPartner in the database.
func (dapc *DepositAddressPartnerCreate) Save(ctx context.Context) (*DepositAddressPartner, error) {
	dapc.defaults()
	return withHooks(ctx, dapc.sqlSave, dapc.mutation, dapc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dapc *DepositAddressPartnerCreate) SaveX(ctx context.Context) *DepositAddressPartner {
	v, err := dapc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dapc *DepositAddressPartnerCreate) Exec(ctx context.Context) error {
	_, err := dapc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dapc *DepositAddressPartnerCreate) ExecX(ctx context.Context) {
	if err := dapc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dapc *DepositAddressPartnerCreate) defaults() {
	if _, ok := dapc.mutation.CreateTime(); !ok {
		v := depositaddresspartner.DefaultCreateTime()
		dapc.mutation.SetCreateTime(v)
	}
	if _, ok := dapc.mutation.UpdateTime(); !ok {
		v := depositaddresspartner.DefaultUpdateTime()
		dapc.mutation.SetUpdateTime(v)
	}
	if _, ok := dapc.mutation.ID(); !ok {
		v := depositaddresspartner.DefaultID()
		dapc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dapc *DepositAddressPartnerCreate) check() error {
	if _, ok := dapc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "DepositAddressPartner.create_time"`)}
	}
	if _, ok := dapc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "DepositAddressPartner.update_time"`)}
	}
	if len(dapc.mutation.PartnerIDs()) == 0 {
		return &ValidationError{Name: "partner", err: errors.New(`ent: missing required edge "DepositAddressPartner.partner"`)}
	}
	if len(dapc.mutation.DepositAddressIDs()) == 0 {
		return &ValidationError{Name: "deposit_address", err: errors.New(`ent: missing required edge "DepositAddressPartner.deposit_address"`)}
	}
	return nil
}

func (dapc *DepositAddressPartnerCreate) sqlSave(ctx context.Context) (*DepositAddressPartner, error) {
	if err := dapc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dapc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dapc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dapc.mutation.id = &_node.ID
	dapc.mutation.done = true
	return _node, nil
}

func (dapc *DepositAddressPartnerCreate) createSpec() (*DepositAddressPartner, *sqlgraph.CreateSpec) {
	var (
		_node = &DepositAddressPartner{config: dapc.config}
		_spec = sqlgraph.NewCreateSpec(depositaddresspartner.Table, sqlgraph.NewFieldSpec(depositaddresspartner.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = dapc.conflict
	if id, ok := dapc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dapc.mutation.CreateTime(); ok {
		_spec.SetField(depositaddresspartner.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := dapc.mutation.UpdateTime(); ok {
		_spec.SetField(depositaddresspartner.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if nodes := dapc.mutation.PartnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   depositaddresspartner.PartnerTable,
			Columns: []string{depositaddresspartner.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deposit_address_partner_partner = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dapc.mutation.DepositAddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   depositaddresspartner.DepositAddressTable,
			Columns: []string{depositaddresspartner.DepositAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(depositaddress.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deposit_address_partner_deposit_address = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DepositAddressPartner.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DepositAddressPartnerUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (dapc *DepositAddressPartnerCreate) OnConflict(opts ...sql.ConflictOption) *DepositAddressPartnerUpsertOne {
	dapc.conflict = opts
	return &DepositAddressPartnerUpsertOne{
		create: dapc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DepositAddressPartner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dapc *DepositAddressPartnerCreate) OnConflictColumns(columns ...string) *DepositAddressPartnerUpsertOne {
	dapc.conflict = append(dapc.conflict, sql.ConflictColumns(columns...))
	return &DepositAddressPartnerUpsertOne{
		create: dapc,
	}
}

type (
	// DepositAddressPartnerUpsertOne is the builder for "upsert"-ing
	//  one DepositAddressPartner node.
	DepositAddressPartnerUpsertOne struct {
		create *DepositAddressPartnerCreate
	}

	// DepositAddressPartnerUpsert is the "OnConflict" setter.
	DepositAddressPartnerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *DepositAddressPartnerUpsert) SetUpdateTime(v time.Time) *DepositAddressPartnerUpsert {
	u.Set(depositaddresspartner.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DepositAddressPartnerUpsert) UpdateUpdateTime() *DepositAddressPartnerUpsert {
	u.SetExcluded(depositaddresspartner.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DepositAddressPartner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(depositaddresspartner.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DepositAddressPartnerUpsertOne) UpdateNewValues() *DepositAddressPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(depositaddresspartner.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(depositaddresspartner.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DepositAddressPartner.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DepositAddressPartnerUpsertOne) Ignore() *DepositAddressPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DepositAddressPartnerUpsertOne) DoNothing() *DepositAddressPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DepositAddressPartnerCreate.OnConflict
// documentation for more info.
func (u *DepositAddressPartnerUpsertOne) Update(set func(*DepositAddressPartnerUpsert)) *DepositAddressPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DepositAddressPartnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DepositAddressPartnerUpsertOne) SetUpdateTime(v time.Time) *DepositAddressPartnerUpsertOne {
	return u.Update(func(s *DepositAddressPartnerUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DepositAddressPartnerUpsertOne) UpdateUpdateTime() *DepositAddressPartnerUpsertOne {
	return u.Update(func(s *DepositAddressPartnerUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *DepositAddressPartnerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DepositAddressPartnerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DepositAddressPartnerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DepositAddressPartnerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DepositAddressPartnerUpsertOne.ID is not supported by MySQL driver. Use DepositAddressPartnerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DepositAddressPartnerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DepositAddressPartnerCreateBulk is the builder for creating many DepositAddressPartner entities in bulk.
type DepositAddressPartnerCreateBulk struct {
	config
	err      error
	builders []*DepositAddressPartnerCreate
	conflict []sql.ConflictOption
}

// Save creates the DepositAddressPartner entities in the database.
func (dapcb *DepositAddressPartnerCreateBulk) Save(ctx context.Context) ([]*DepositAddressPartner, error) {
	if dapcb.err != nil {
		return nil, dapcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dapcb.builders))
	nodes := make([]*DepositAddressPartner, len(dapcb.builders))
	mutators := make([]Mutator, len(dapcb.builders))
	for i := range dapcb.builders {
		func(i int, root context.Context) {
			builder := dapcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepositAddressPartnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dapcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dapcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dapcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dapcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dapcb *DepositAddressPartnerCreateBulk) SaveX(ctx context.Context) []*DepositAddressPartner {
	v, err := dapcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dapcb *DepositAddressPartnerCreateBulk) Exec(ctx context.Context) error {
	_, err := dapcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dapcb *DepositAddressPartnerCreateBulk) ExecX(ctx context.Context) {
	if err := dapcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DepositAddressPartner.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DepositAddressPartnerUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (dapcb *DepositAddressPartnerCreateBulk) OnConflict(opts ...sql.ConflictOption) *DepositAddressPartnerUpsertBulk {
	dapcb.conflict = opts
	return &DepositAddressPartnerUpsertBulk{
		create: dapcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DepositAddressPartner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dapcb *DepositAddressPartnerCreateBulk) OnConflictColumns(columns ...string) *DepositAddressPartnerUpsertBulk {
	dapcb.conflict = append(dapcb.conflict, sql.ConflictColumns(columns...))
	return &DepositAddressPartnerUpsertBulk{
		create: dapcb,
	}
}

// DepositAddressPartnerUpsertBulk is the builder for "upsert"-ing
// a bulk of DepositAddressPartner nodes.
type DepositAddressPartnerUpsertBulk struct {
	create *DepositAddressPartnerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DepositAddressPartner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(depositaddresspartner.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DepositAddressPartnerUpsertBulk) UpdateNewValues() *DepositAddressPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(depositaddresspartner.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(depositaddresspartner.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DepositAddressPartner.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DepositAddressPartnerUpsertBulk) Ignore() *DepositAddressPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DepositAddressPartnerUpsertBulk) DoNothing() *DepositAddressPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DepositAddressPartnerCreateBulk.OnConflict
// documentation for more info.
func (u *DepositAddressPartnerUpsertBulk) Update(set func(*DepositAddressPartnerUpsert)) *DepositAddressPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DepositAddressPartnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DepositAddressPartnerUpsertBulk) SetUpdateTime(v time.Time) *DepositAddressPartnerUpsertBulk {
	return u.Update(func(s *DepositAddressPartnerUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DepositAddressPartnerUpsertBulk) UpdateUpdateTime() *DepositAddressPartnerUpsertBulk {
	return u.Update(func(s *DepositAddressPartnerUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *DepositAddressPartnerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DepositAddressPartnerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DepositAddressPartnerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DepositAddressPartnerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
