// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/depositaddress"
	"github.com/lightsparkdev/spark/so/ent/depositaddresspartner"
	"github.com/lightsparkdev/spark/so/ent/partner"
)

// DepositAddressPartner is the model entity for the DepositAddressPartner schema.
type DepositAddressPartner struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DepositAddressPartnerQuery when eager-loading is set.
	Edges                                   DepositAddressPartnerEdges `json:"edges"`
	deposit_address_partner_partner         *uuid.UUID
	deposit_address_partner_deposit_address *uuid.UUID
	selectValues                            sql.SelectValues
}

// DepositAddressPartnerEdges holds the relations/edges for other nodes in the graph.
type DepositAddressPartnerEdges struct {
	// The partner that generated this deposit address.
	Partner *Partner `json:"partner,omitempty"`
	// The deposit address associated with this partner.
	DepositAddress *DepositAddress `json:"deposit_address,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PartnerOrErr returns the Partner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepositAddressPartnerEdges) PartnerOrErr() (*Partner, error) {
	if e.Partner != nil {
		return e.Partner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: partner.Label}
	}
	return nil, &NotLoadedError{edge: "partner"}
}

// DepositAddressOrErr returns the DepositAddress value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepositAddressPartnerEdges) DepositAddressOrErr() (*DepositAddress, error) {
	if e.DepositAddress != nil {
		return e.DepositAddress, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: depositaddress.Label}
	}
	return nil, &NotLoadedError{edge: "deposit_address"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DepositAddressPartner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case depositaddresspartner.FieldCreateTime, depositaddresspartner.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case depositaddresspartner.FieldID:
			values[i] = new(uuid.UUID)
		case depositaddresspartner.ForeignKeys[0]: // deposit_address_partner_partner
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case depositaddresspartner.ForeignKeys[1]: // deposit_address_partner_deposit_address
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DepositAddressPartner fields.
func (dap *DepositAddressPartner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case depositaddresspartner.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dap.ID = *value
			}
		case depositaddresspartner.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				dap.CreateTime = value.Time
			}
		case depositaddresspartner.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				dap.UpdateTime = value.Time
			}
		case depositaddresspartner.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deposit_address_partner_partner", values[i])
			} else if value.Valid {
				dap.deposit_address_partner_partner = new(uuid.UUID)
				*dap.deposit_address_partner_partner = *value.S.(*uuid.UUID)
			}
		case depositaddresspartner.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deposit_address_partner_deposit_address", values[i])
			} else if value.Valid {
				dap.deposit_address_partner_deposit_address = new(uuid.UUID)
				*dap.deposit_address_partner_deposit_address = *value.S.(*uuid.UUID)
			}
		default:
			dap.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DepositAddressPartner.
// This includes values selected through modifiers, order, etc.
func (dap *DepositAddressPartner) Value(name string) (ent.Value, error) {
	return dap.selectValues.Get(name)
}

// QueryPartner queries the "partner" edge of the DepositAddressPartner entity.
func (dap *DepositAddressPartner) QueryPartner() *PartnerQuery {
	return NewDepositAddressPartnerClient(dap.config).QueryPartner(dap)
}

// QueryDepositAddress queries the "deposit_address" edge of the DepositAddressPartner entity.
func (dap *DepositAddressPartner) QueryDepositAddress() *DepositAddressQuery {
	return NewDepositAddressPartnerClient(dap.config).QueryDepositAddress(dap)
}

// Update returns a builder for updating this DepositAddressPartner.
// Note that you need to call DepositAddressPartner.Unwrap() before calling this method if this DepositAddressPartner
// was returned from a transaction, and the transaction was committed or rolled back.
func (dap *DepositAddressPartner) Update() *DepositAddressPartnerUpdateOne {
	return NewDepositAddressPartnerClient(dap.config).UpdateOne(dap)
}

// Unwrap unwraps the DepositAddressPartner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dap *DepositAddressPartner) Unwrap() *DepositAddressPartner {
	_tx, ok := dap.config.driver.(*txDriver)
	if !ok {
		panic("ent: DepositAddressPartner is not a transactional entity")
	}
	dap.config.driver = _tx.drv
	return dap
}

// String implements the fmt.Stringer.
func (dap *DepositAddressPartner) String() string {
	var builder strings.Builder
	builder.WriteString("DepositAddressPartner(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dap.ID))
	builder.WriteString("create_time=")
	builder.WriteString(dap.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(dap.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DepositAddressPartners is a parsable slice of DepositAddressPartner.
type DepositAddressPartners []*DepositAddressPartner
