// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/depositaddresspartner"
	"github.com/lightsparkdev/spark/so/ent/partner"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// DepositAddressPartnerUpdate is the builder for updating DepositAddressPartner entities.
type DepositAddressPartnerUpdate struct {
	config
	hooks     []Hook
	mutation  *DepositAddressPartnerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DepositAddressPartnerUpdate builder.
func (dapu *DepositAddressPartnerUpdate) Where(ps ...predicate.DepositAddressPartner) *DepositAddressPartnerUpdate {
	dapu.mutation.Where(ps...)
	return dapu
}

// SetUpdateTime sets the "update_time" field.
func (dapu *DepositAddressPartnerUpdate) SetUpdateTime(t time.Time) *DepositAddressPartnerUpdate {
	dapu.mutation.SetUpdateTime(t)
	return dapu
}

// SetPartnerID sets the "partner" edge to the Partner entity by ID.
func (dapu *DepositAddressPartnerUpdate) SetPartnerID(id uuid.UUID) *DepositAddressPartnerUpdate {
	dapu.mutation.SetPartnerID(id)
	return dapu
}

// SetPartner sets the "partner" edge to the Partner entity.
func (dapu *DepositAddressPartnerUpdate) SetPartner(p *Partner) *DepositAddressPartnerUpdate {
	return dapu.SetPartnerID(p.ID)
}

// Mutation returns the DepositAddressPartnerMutation object of the builder.
func (dapu *DepositAddressPartnerUpdate) Mutation() *DepositAddressPartnerMutation {
	return dapu.mutation
}

// ClearPartner clears the "partner" edge to the Partner entity.
func (dapu *DepositAddressPartnerUpdate) ClearPartner() *DepositAddressPartnerUpdate {
	dapu.mutation.ClearPartner()
	return dapu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dapu *DepositAddressPartnerUpdate) Save(ctx context.Context) (int, error) {
	dapu.defaults()
	return withHooks(ctx, dapu.sqlSave, dapu.mutation, dapu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dapu *DepositAddressPartnerUpdate) SaveX(ctx context.Context) int {
	affected, err := dapu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dapu *DepositAddressPartnerUpdate) Exec(ctx context.Context) error {
	_, err := dapu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dapu *DepositAddressPartnerUpdate) ExecX(ctx context.Context) {
	if err := dapu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dapu *DepositAddressPartnerUpdate) defaults() {
	if _, ok := dapu.mutation.UpdateTime(); !ok {
		v := depositaddresspartner.UpdateDefaultUpdateTime()
		dapu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dapu *DepositAddressPartnerUpdate) check() error {
	if dapu.mutation.PartnerCleared() && len(dapu.mutation.PartnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepositAddressPartner.partner"`)
	}
	if dapu.mutation.DepositAddressCleared() && len(dapu.mutation.DepositAddressIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepositAddressPartner.deposit_address"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (dapu *DepositAddressPartnerUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DepositAddressPartnerUpdate {
	dapu.modifiers = append(dapu.modifiers, modifiers...)
	return dapu
}

func (dapu *DepositAddressPartnerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dapu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(depositaddresspartner.Table, depositaddresspartner.Columns, sqlgraph.NewFieldSpec(depositaddresspartner.FieldID, field.TypeUUID))
	if ps := dapu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dapu.mutation.UpdateTime(); ok {
		_spec.SetField(depositaddresspartner.FieldUpdateTime, field.TypeTime, value)
	}
	if dapu.mutation.PartnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   depositaddresspartner.PartnerTable,
			Columns: []string{depositaddresspartner.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dapu.mutation.PartnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   depositaddresspartner.PartnerTable,
			Columns: []string{depositaddresspartner.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(dapu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, dapu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{depositaddresspartner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dapu.mutation.done = true
	return n, nil
}

// DepositAddressPartnerUpdateOne is the builder for updating a single DepositAddressPartner entity.
type DepositAddressPartnerUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DepositAddressPartnerMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (dapuo *DepositAddressPartnerUpdateOne) SetUpdateTime(t time.Time) *DepositAddressPartnerUpdateOne {
	dapuo.mutation.SetUpdateTime(t)
	return dapuo
}

// SetPartnerID sets the "partner" edge to the Partner entity by ID.
func (dapuo *DepositAddressPartnerUpdateOne) SetPartnerID(id uuid.UUID) *DepositAddressPartnerUpdateOne {
	dapuo.mutation.SetPartnerID(id)
	return dapuo
}

// SetPartner sets the "partner" edge to the Partner entity.
func (dapuo *DepositAddressPartnerUpdateOne) SetPartner(p *Partner) *DepositAddressPartnerUpdateOne {
	return dapuo.SetPartnerID(p.ID)
}

// Mutation returns the DepositAddressPartnerMutation object of the builder.
func (dapuo *DepositAddressPartnerUpdateOne) Mutation() *DepositAddressPartnerMutation {
	return dapuo.mutation
}

// ClearPartner clears the "partner" edge to the Partner entity.
func (dapuo *DepositAddressPartnerUpdateOne) ClearPartner() *DepositAddressPartnerUpdateOne {
	dapuo.mutation.ClearPartner()
	return dapuo
}

// Where appends a list predicates to the DepositAddressPartnerUpdate builder.
func (dapuo *DepositAddressPartnerUpdateOne) Where(ps ...predicate.DepositAddressPartner) *DepositAddressPartnerUpdateOne {
	dapuo.mutation.Where(ps...)
	return dapuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dapuo *DepositAddressPartnerUpdateOne) Select(field string, fields ...string) *DepositAddressPartnerUpdateOne {
	dapuo.fields = append([]string{field}, fields...)
	return dapuo
}

// Save executes the query and returns the updated DepositAddressPartner entity.
func (dapuo *DepositAddressPartnerUpdateOne) Save(ctx context.Context) (*DepositAddressPartner, error) {
	dapuo.defaults()
	return withHooks(ctx, dapuo.sqlSave, dapuo.mutation, dapuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dapuo *DepositAddressPartnerUpdateOne) SaveX(ctx context.Context) *DepositAddressPartner {
	node, err := dapuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dapuo *DepositAddressPartnerUpdateOne) Exec(ctx context.Context) error {
	_, err := dapuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dapuo *DepositAddressPartnerUpdateOne) ExecX(ctx context.Context) {
	if err := dapuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dapuo *DepositAddressPartnerUpdateOne) defaults() {
	if _, ok := dapuo.mutation.UpdateTime(); !ok {
		v := depositaddresspartner.UpdateDefaultUpdateTime()
		dapuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dapuo *DepositAddressPartnerUpdateOne) check() error {
	if dapuo.mutation.PartnerCleared() && len(dapuo.mutation.PartnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepositAddressPartner.partner"`)
	}
	if dapuo.mutation.DepositAddressCleared() && len(dapuo.mutation.DepositAddressIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DepositAddressPartner.deposit_address"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (dapuo *DepositAddressPartnerUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DepositAddressPartnerUpdateOne {
	dapuo.modifiers = append(dapuo.modifiers, modifiers...)
	return dapuo
}

func (dapuo *DepositAddressPartnerUpdateOne) sqlSave(ctx context.Context) (_node *DepositAddressPartner, err error) {
	if err := dapuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(depositaddresspartner.Table, depositaddresspartner.Columns, sqlgraph.NewFieldSpec(depositaddresspartner.FieldID, field.TypeUUID))
	id, ok := dapuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DepositAddressPartner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dapuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, depositaddresspartner.FieldID)
		for _, f := range fields {
			if !depositaddresspartner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != depositaddresspartner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dapuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dapuo.mutation.UpdateTime(); ok {
		_spec.SetField(depositaddresspartner.FieldUpdateTime, field.TypeTime, value)
	}
	if dapuo.mutation.PartnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   depositaddresspartner.PartnerTable,
			Columns: []string{depositaddresspartner.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dapuo.mutation.PartnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   depositaddresspartner.PartnerTable,
			Columns: []string{depositaddresspartner.PartnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(dapuo.modifiers...)
	_node = &DepositAddressPartner{config: dapuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dapuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{depositaddresspartner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dapuo.mutation.done = true
	return _node, nil
}
