// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/flowexecution"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// FlowExecutionQuery is the builder for querying FlowExecution entities.
type FlowExecutionQuery struct {
	config
	ctx        *QueryContext
	order      []flowexecution.OrderOption
	inters     []Interceptor
	predicates []predicate.FlowExecution
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FlowExecutionQuery builder.
func (feq *FlowExecutionQuery) Where(ps ...predicate.FlowExecution) *FlowExecutionQuery {
	feq.predicates = append(feq.predicates, ps...)
	return feq
}

// Limit the number of records to be returned by this query.
func (feq *FlowExecutionQuery) Limit(limit int) *FlowExecutionQuery {
	feq.ctx.Limit = &limit
	return feq
}

// Offset to start from.
func (feq *FlowExecutionQuery) Offset(offset int) *FlowExecutionQuery {
	feq.ctx.Offset = &offset
	return feq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (feq *FlowExecutionQuery) Unique(unique bool) *FlowExecutionQuery {
	feq.ctx.Unique = &unique
	return feq
}

// Order specifies how the records should be ordered.
func (feq *FlowExecutionQuery) Order(o ...flowexecution.OrderOption) *FlowExecutionQuery {
	feq.order = append(feq.order, o...)
	return feq
}

// First returns the first FlowExecution entity from the query.
// Returns a *NotFoundError when no FlowExecution was found.
func (feq *FlowExecutionQuery) First(ctx context.Context) (*FlowExecution, error) {
	nodes, err := feq.Limit(1).All(setContextOp(ctx, feq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{flowexecution.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (feq *FlowExecutionQuery) FirstX(ctx context.Context) *FlowExecution {
	node, err := feq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FlowExecution ID from the query.
// Returns a *NotFoundError when no FlowExecution ID was found.
func (feq *FlowExecutionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = feq.Limit(1).IDs(setContextOp(ctx, feq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{flowexecution.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (feq *FlowExecutionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := feq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FlowExecution entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FlowExecution entity is found.
// Returns a *NotFoundError when no FlowExecution entities are found.
func (feq *FlowExecutionQuery) Only(ctx context.Context) (*FlowExecution, error) {
	nodes, err := feq.Limit(2).All(setContextOp(ctx, feq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{flowexecution.Label}
	default:
		return nil, &NotSingularError{flowexecution.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (feq *FlowExecutionQuery) OnlyX(ctx context.Context) *FlowExecution {
	node, err := feq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FlowExecution ID in the query.
// Returns a *NotSingularError when more than one FlowExecution ID is found.
// Returns a *NotFoundError when no entities are found.
func (feq *FlowExecutionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = feq.Limit(2).IDs(setContextOp(ctx, feq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{flowexecution.Label}
	default:
		err = &NotSingularError{flowexecution.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (feq *FlowExecutionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := feq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FlowExecutions.
func (feq *FlowExecutionQuery) All(ctx context.Context) ([]*FlowExecution, error) {
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryAll)
	if err := feq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FlowExecution, *FlowExecutionQuery]()
	return withInterceptors[[]*FlowExecution](ctx, feq, qr, feq.inters)
}

// AllX is like All, but panics if an error occurs.
func (feq *FlowExecutionQuery) AllX(ctx context.Context) []*FlowExecution {
	nodes, err := feq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FlowExecution IDs.
func (feq *FlowExecutionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if feq.ctx.Unique == nil && feq.path != nil {
		feq.Unique(true)
	}
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryIDs)
	if err = feq.Select(flowexecution.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (feq *FlowExecutionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := feq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (feq *FlowExecutionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryCount)
	if err := feq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, feq, querierCount[*FlowExecutionQuery](), feq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (feq *FlowExecutionQuery) CountX(ctx context.Context) int {
	count, err := feq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (feq *FlowExecutionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryExist)
	switch _, err := feq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (feq *FlowExecutionQuery) ExistX(ctx context.Context) bool {
	exist, err := feq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FlowExecutionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (feq *FlowExecutionQuery) Clone() *FlowExecutionQuery {
	if feq == nil {
		return nil
	}
	return &FlowExecutionQuery{
		config:     feq.config,
		ctx:        feq.ctx.Clone(),
		order:      append([]flowexecution.OrderOption{}, feq.order...),
		inters:     append([]Interceptor{}, feq.inters...),
		predicates: append([]predicate.FlowExecution{}, feq.predicates...),
		// clone intermediate query.
		sql:       feq.sql.Clone(),
		path:      feq.path,
		modifiers: append([]func(*sql.Selector){}, feq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FlowExecution.Query().
//		GroupBy(flowexecution.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (feq *FlowExecutionQuery) GroupBy(field string, fields ...string) *FlowExecutionGroupBy {
	feq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FlowExecutionGroupBy{build: feq}
	grbuild.flds = &feq.ctx.Fields
	grbuild.label = flowexecution.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.FlowExecution.Query().
//		Select(flowexecution.FieldCreateTime).
//		Scan(ctx, &v)
func (feq *FlowExecutionQuery) Select(fields ...string) *FlowExecutionSelect {
	feq.ctx.Fields = append(feq.ctx.Fields, fields...)
	sbuild := &FlowExecutionSelect{FlowExecutionQuery: feq}
	sbuild.label = flowexecution.Label
	sbuild.flds, sbuild.scan = &feq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FlowExecutionSelect configured with the given aggregations.
func (feq *FlowExecutionQuery) Aggregate(fns ...AggregateFunc) *FlowExecutionSelect {
	return feq.Select().Aggregate(fns...)
}

func (feq *FlowExecutionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range feq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, feq); err != nil {
				return err
			}
		}
	}
	for _, f := range feq.ctx.Fields {
		if !flowexecution.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if feq.path != nil {
		prev, err := feq.path(ctx)
		if err != nil {
			return err
		}
		feq.sql = prev
	}
	return nil
}

func (feq *FlowExecutionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FlowExecution, error) {
	var (
		nodes = []*FlowExecution{}
		_spec = feq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FlowExecution).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FlowExecution{config: feq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(feq.modifiers) > 0 {
		_spec.Modifiers = feq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, feq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (feq *FlowExecutionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := feq.querySpec()
	if len(feq.modifiers) > 0 {
		_spec.Modifiers = feq.modifiers
	}
	_spec.Node.Columns = feq.ctx.Fields
	if len(feq.ctx.Fields) > 0 {
		_spec.Unique = feq.ctx.Unique != nil && *feq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, feq.driver, _spec)
}

func (feq *FlowExecutionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(flowexecution.Table, flowexecution.Columns, sqlgraph.NewFieldSpec(flowexecution.FieldID, field.TypeUUID))
	_spec.From = feq.sql
	if unique := feq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if feq.path != nil {
		_spec.Unique = true
	}
	if fields := feq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flowexecution.FieldID)
		for i := range fields {
			if fields[i] != flowexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := feq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := feq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := feq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := feq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (feq *FlowExecutionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(feq.driver.Dialect())
	t1 := builder.Table(flowexecution.Table)
	columns := feq.ctx.Fields
	if len(columns) == 0 {
		columns = flowexecution.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if feq.sql != nil {
		selector = feq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if feq.ctx.Unique != nil && *feq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range feq.modifiers {
		m(selector)
	}
	for _, p := range feq.predicates {
		p(selector)
	}
	for _, p := range feq.order {
		p(selector)
	}
	if offset := feq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := feq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (feq *FlowExecutionQuery) ForUpdate(opts ...sql.LockOption) *FlowExecutionQuery {
	if feq.driver.Dialect() == dialect.Postgres {
		feq.Unique(false)
	}
	feq.modifiers = append(feq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return feq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (feq *FlowExecutionQuery) ForShare(opts ...sql.LockOption) *FlowExecutionQuery {
	if feq.driver.Dialect() == dialect.Postgres {
		feq.Unique(false)
	}
	feq.modifiers = append(feq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return feq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (feq *FlowExecutionQuery) Modify(modifiers ...func(s *sql.Selector)) *FlowExecutionSelect {
	feq.modifiers = append(feq.modifiers, modifiers...)
	return feq.Select()
}

// FlowExecutionGroupBy is the group-by builder for FlowExecution entities.
type FlowExecutionGroupBy struct {
	selector
	build *FlowExecutionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fegb *FlowExecutionGroupBy) Aggregate(fns ...AggregateFunc) *FlowExecutionGroupBy {
	fegb.fns = append(fegb.fns, fns...)
	return fegb
}

// Scan applies the selector query and scans the result into the given value.
func (fegb *FlowExecutionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fegb.build.ctx, ent.OpQueryGroupBy)
	if err := fegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FlowExecutionQuery, *FlowExecutionGroupBy](ctx, fegb.build, fegb, fegb.build.inters, v)
}

func (fegb *FlowExecutionGroupBy) sqlScan(ctx context.Context, root *FlowExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fegb.fns))
	for _, fn := range fegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fegb.flds)+len(fegb.fns))
		for _, f := range *fegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FlowExecutionSelect is the builder for selecting fields of FlowExecution entities.
type FlowExecutionSelect struct {
	*FlowExecutionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fes *FlowExecutionSelect) Aggregate(fns ...AggregateFunc) *FlowExecutionSelect {
	fes.fns = append(fes.fns, fns...)
	return fes
}

// Scan applies the selector query and scans the result into the given value.
func (fes *FlowExecutionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fes.ctx, ent.OpQuerySelect)
	if err := fes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FlowExecutionQuery, *FlowExecutionSelect](ctx, fes.FlowExecutionQuery, fes, fes.inters, v)
}

func (fes *FlowExecutionSelect) sqlScan(ctx context.Context, root *FlowExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fes.fns))
	for _, fn := range fes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fes *FlowExecutionSelect) Modify(modifiers ...func(s *sql.Selector)) *FlowExecutionSelect {
	fes.modifiers = append(fes.modifiers, modifiers...)
	return fes
}
