// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/flowexecution"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// FlowExecutionCreate is the builder for creating a FlowExecution entity.
type FlowExecutionCreate struct {
	config
	mutation *FlowExecutionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (fec *FlowExecutionCreate) SetCreateTime(t time.Time) *FlowExecutionCreate {
	fec.mutation.SetCreateTime(t)
	return fec
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (fec *FlowExecutionCreate) SetNillableCreateTime(t *time.Time) *FlowExecutionCreate {
	if t != nil {
		fec.SetCreateTime(*t)
	}
	return fec
}

// SetUpdateTime sets the "update_time" field.
func (fec *FlowExecutionCreate) SetUpdateTime(t time.Time) *FlowExecutionCreate {
	fec.mutation.SetUpdateTime(t)
	return fec
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (fec *FlowExecutionCreate) SetNillableUpdateTime(t *time.Time) *FlowExecutionCreate {
	if t != nil {
		fec.SetUpdateTime(*t)
	}
	return fec
}

// SetRole sets the "role" field.
func (fec *FlowExecutionCreate) SetRole(ser schematype.FlowExecutionRole) *FlowExecutionCreate {
	fec.mutation.SetRole(ser)
	return fec
}

// SetOpType sets the "op_type" field.
func (fec *FlowExecutionCreate) SetOpType(i int32) *FlowExecutionCreate {
	fec.mutation.SetOpType(i)
	return fec
}

// SetStatus sets the "status" field.
func (fec *FlowExecutionCreate) SetStatus(ses schematype.FlowExecutionStatus) *FlowExecutionCreate {
	fec.mutation.SetStatus(ses)
	return fec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fec *FlowExecutionCreate) SetNillableStatus(ses *schematype.FlowExecutionStatus) *FlowExecutionCreate {
	if ses != nil {
		fec.SetStatus(*ses)
	}
	return fec
}

// SetCoordinatorIndex sets the "coordinator_index" field.
func (fec *FlowExecutionCreate) SetCoordinatorIndex(u uint) *FlowExecutionCreate {
	fec.mutation.SetCoordinatorIndex(u)
	return fec
}

// SetDecisionPayload sets the "decision_payload" field.
func (fec *FlowExecutionCreate) SetDecisionPayload(b []byte) *FlowExecutionCreate {
	fec.mutation.SetDecisionPayload(b)
	return fec
}

// SetID sets the "id" field.
func (fec *FlowExecutionCreate) SetID(u uuid.UUID) *FlowExecutionCreate {
	fec.mutation.SetID(u)
	return fec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fec *FlowExecutionCreate) SetNillableID(u *uuid.UUID) *FlowExecutionCreate {
	if u != nil {
		fec.SetID(*u)
	}
	return fec
}

// Mutation returns the FlowExecutionMutation object of the builder.
func (fec *FlowExecutionCreate) Mutation() *FlowExecutionMutation {
	return fec.mutation
}

// Save creates the FlowExecution in the database.
func (fec *FlowExecutionCreate) Save(ctx context.Context) (*FlowExecution, error) {
	if err := fec.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fec.sqlSave, fec.mutation, fec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fec *FlowExecutionCreate) SaveX(ctx context.Context) *FlowExecution {
	v, err := fec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fec *FlowExecutionCreate) Exec(ctx context.Context) error {
	_, err := fec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fec *FlowExecutionCreate) ExecX(ctx context.Context) {
	if err := fec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fec *FlowExecutionCreate) defaults() error {
	if _, ok := fec.mutation.CreateTime(); !ok {
		if flowexecution.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized flowexecution.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := flowexecution.DefaultCreateTime()
		fec.mutation.SetCreateTime(v)
	}
	if _, ok := fec.mutation.UpdateTime(); !ok {
		if flowexecution.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized flowexecution.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := flowexecution.DefaultUpdateTime()
		fec.mutation.SetUpdateTime(v)
	}
	if _, ok := fec.mutation.Status(); !ok {
		v := flowexecution.DefaultStatus
		fec.mutation.SetStatus(v)
	}
	if _, ok := fec.mutation.ID(); !ok {
		if flowexecution.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized flowexecution.DefaultID (forgotten import ent/runtime?)")
		}
		v := flowexecution.DefaultID()
		fec.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fec *FlowExecutionCreate) check() error {
	if _, ok := fec.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "FlowExecution.create_time"`)}
	}
	if _, ok := fec.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "FlowExecution.update_time"`)}
	}
	if _, ok := fec.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "FlowExecution.role"`)}
	}
	if v, ok := fec.mutation.Role(); ok {
		if err := flowexecution.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "FlowExecution.role": %w`, err)}
		}
	}
	if _, ok := fec.mutation.OpType(); !ok {
		return &ValidationError{Name: "op_type", err: errors.New(`ent: missing required field "FlowExecution.op_type"`)}
	}
	if _, ok := fec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FlowExecution.status"`)}
	}
	if v, ok := fec.mutation.Status(); ok {
		if err := flowexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FlowExecution.status": %w`, err)}
		}
	}
	if _, ok := fec.mutation.CoordinatorIndex(); !ok {
		return &ValidationError{Name: "coordinator_index", err: errors.New(`ent: missing required field "FlowExecution.coordinator_index"`)}
	}
	return nil
}

func (fec *FlowExecutionCreate) sqlSave(ctx context.Context) (*FlowExecution, error) {
	if err := fec.check(); err != nil {
		return nil, err
	}
	_node, _spec := fec.createSpec()
	if err := sqlgraph.CreateNode(ctx, fec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	fec.mutation.id = &_node.ID
	fec.mutation.done = true
	return _node, nil
}

func (fec *FlowExecutionCreate) createSpec() (*FlowExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &FlowExecution{config: fec.config}
		_spec = sqlgraph.NewCreateSpec(flowexecution.Table, sqlgraph.NewFieldSpec(flowexecution.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = fec.conflict
	if id, ok := fec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := fec.mutation.CreateTime(); ok {
		_spec.SetField(flowexecution.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := fec.mutation.UpdateTime(); ok {
		_spec.SetField(flowexecution.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := fec.mutation.Role(); ok {
		_spec.SetField(flowexecution.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := fec.mutation.OpType(); ok {
		_spec.SetField(flowexecution.FieldOpType, field.TypeInt32, value)
		_node.OpType = value
	}
	if value, ok := fec.mutation.Status(); ok {
		_spec.SetField(flowexecution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := fec.mutation.CoordinatorIndex(); ok {
		_spec.SetField(flowexecution.FieldCoordinatorIndex, field.TypeUint, value)
		_node.CoordinatorIndex = value
	}
	if value, ok := fec.mutation.DecisionPayload(); ok {
		_spec.SetField(flowexecution.FieldDecisionPayload, field.TypeBytes, value)
		_node.DecisionPayload = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FlowExecution.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlowExecutionUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (fec *FlowExecutionCreate) OnConflict(opts ...sql.ConflictOption) *FlowExecutionUpsertOne {
	fec.conflict = opts
	return &FlowExecutionUpsertOne{
		create: fec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FlowExecution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fec *FlowExecutionCreate) OnConflictColumns(columns ...string) *FlowExecutionUpsertOne {
	fec.conflict = append(fec.conflict, sql.ConflictColumns(columns...))
	return &FlowExecutionUpsertOne{
		create: fec,
	}
}

type (
	// FlowExecutionUpsertOne is the builder for "upsert"-ing
	//  one FlowExecution node.
	FlowExecutionUpsertOne struct {
		create *FlowExecutionCreate
	}

	// FlowExecutionUpsert is the "OnConflict" setter.
	FlowExecutionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *FlowExecutionUpsert) SetUpdateTime(v time.Time) *FlowExecutionUpsert {
	u.Set(flowexecution.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FlowExecutionUpsert) UpdateUpdateTime() *FlowExecutionUpsert {
	u.SetExcluded(flowexecution.FieldUpdateTime)
	return u
}

// SetStatus sets the "status" field.
func (u *FlowExecutionUpsert) SetStatus(v schematype.FlowExecutionStatus) *FlowExecutionUpsert {
	u.Set(flowexecution.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FlowExecutionUpsert) UpdateStatus() *FlowExecutionUpsert {
	u.SetExcluded(flowexecution.FieldStatus)
	return u
}

// SetDecisionPayload sets the "decision_payload" field.
func (u *FlowExecutionUpsert) SetDecisionPayload(v []byte) *FlowExecutionUpsert {
	u.Set(flowexecution.FieldDecisionPayload, v)
	return u
}

// UpdateDecisionPayload sets the "decision_payload" field to the value that was provided on create.
func (u *FlowExecutionUpsert) UpdateDecisionPayload() *FlowExecutionUpsert {
	u.SetExcluded(flowexecution.FieldDecisionPayload)
	return u
}

// ClearDecisionPayload clears the value of the "decision_payload" field.
func (u *FlowExecutionUpsert) ClearDecisionPayload() *FlowExecutionUpsert {
	u.SetNull(flowexecution.FieldDecisionPayload)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.FlowExecution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(flowexecution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FlowExecutionUpsertOne) UpdateNewValues() *FlowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(flowexecution.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(flowexecution.FieldCreateTime)
		}
		if _, exists := u.create.mutation.Role(); exists {
			s.SetIgnore(flowexecution.FieldRole)
		}
		if _, exists := u.create.mutation.OpType(); exists {
			s.SetIgnore(flowexecution.FieldOpType)
		}
		if _, exists := u.create.mutation.CoordinatorIndex(); exists {
			s.SetIgnore(flowexecution.FieldCoordinatorIndex)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FlowExecution.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FlowExecutionUpsertOne) Ignore() *FlowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlowExecutionUpsertOne) DoNothing() *FlowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlowExecutionCreate.OnConflict
// documentation for more info.
func (u *FlowExecutionUpsertOne) Update(set func(*FlowExecutionUpsert)) *FlowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlowExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FlowExecutionUpsertOne) SetUpdateTime(v time.Time) *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FlowExecutionUpsertOne) UpdateUpdateTime() *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *FlowExecutionUpsertOne) SetStatus(v schematype.FlowExecutionStatus) *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FlowExecutionUpsertOne) UpdateStatus() *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.UpdateStatus()
	})
}

// SetDecisionPayload sets the "decision_payload" field.
func (u *FlowExecutionUpsertOne) SetDecisionPayload(v []byte) *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.SetDecisionPayload(v)
	})
}

// UpdateDecisionPayload sets the "decision_payload" field to the value that was provided on create.
func (u *FlowExecutionUpsertOne) UpdateDecisionPayload() *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.UpdateDecisionPayload()
	})
}

// ClearDecisionPayload clears the value of the "decision_payload" field.
func (u *FlowExecutionUpsertOne) ClearDecisionPayload() *FlowExecutionUpsertOne {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.ClearDecisionPayload()
	})
}

// Exec executes the query.
func (u *FlowExecutionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlowExecutionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlowExecutionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FlowExecutionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FlowExecutionUpsertOne.ID is not supported by MySQL driver. Use FlowExecutionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FlowExecutionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FlowExecutionCreateBulk is the builder for creating many FlowExecution entities in bulk.
type FlowExecutionCreateBulk struct {
	config
	err      error
	builders []*FlowExecutionCreate
	conflict []sql.ConflictOption
}

// Save creates the FlowExecution entities in the database.
func (fecb *FlowExecutionCreateBulk) Save(ctx context.Context) ([]*FlowExecution, error) {
	if fecb.err != nil {
		return nil, fecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fecb.builders))
	nodes := make([]*FlowExecution, len(fecb.builders))
	mutators := make([]Mutator, len(fecb.builders))
	for i := range fecb.builders {
		func(i int, root context.Context) {
			builder := fecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlowExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = fecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fecb *FlowExecutionCreateBulk) SaveX(ctx context.Context) []*FlowExecution {
	v, err := fecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fecb *FlowExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := fecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fecb *FlowExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := fecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FlowExecution.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlowExecutionUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (fecb *FlowExecutionCreateBulk) OnConflict(opts ...sql.ConflictOption) *FlowExecutionUpsertBulk {
	fecb.conflict = opts
	return &FlowExecutionUpsertBulk{
		create: fecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FlowExecution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fecb *FlowExecutionCreateBulk) OnConflictColumns(columns ...string) *FlowExecutionUpsertBulk {
	fecb.conflict = append(fecb.conflict, sql.ConflictColumns(columns...))
	return &FlowExecutionUpsertBulk{
		create: fecb,
	}
}

// FlowExecutionUpsertBulk is the builder for "upsert"-ing
// a bulk of FlowExecution nodes.
type FlowExecutionUpsertBulk struct {
	create *FlowExecutionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FlowExecution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(flowexecution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FlowExecutionUpsertBulk) UpdateNewValues() *FlowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(flowexecution.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(flowexecution.FieldCreateTime)
			}
			if _, exists := b.mutation.Role(); exists {
				s.SetIgnore(flowexecution.FieldRole)
			}
			if _, exists := b.mutation.OpType(); exists {
				s.SetIgnore(flowexecution.FieldOpType)
			}
			if _, exists := b.mutation.CoordinatorIndex(); exists {
				s.SetIgnore(flowexecution.FieldCoordinatorIndex)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FlowExecution.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FlowExecutionUpsertBulk) Ignore() *FlowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlowExecutionUpsertBulk) DoNothing() *FlowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlowExecutionCreateBulk.OnConflict
// documentation for more info.
func (u *FlowExecutionUpsertBulk) Update(set func(*FlowExecutionUpsert)) *FlowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlowExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FlowExecutionUpsertBulk) SetUpdateTime(v time.Time) *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FlowExecutionUpsertBulk) UpdateUpdateTime() *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *FlowExecutionUpsertBulk) SetStatus(v schematype.FlowExecutionStatus) *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FlowExecutionUpsertBulk) UpdateStatus() *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.UpdateStatus()
	})
}

// SetDecisionPayload sets the "decision_payload" field.
func (u *FlowExecutionUpsertBulk) SetDecisionPayload(v []byte) *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.SetDecisionPayload(v)
	})
}

// UpdateDecisionPayload sets the "decision_payload" field to the value that was provided on create.
func (u *FlowExecutionUpsertBulk) UpdateDecisionPayload() *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.UpdateDecisionPayload()
	})
}

// ClearDecisionPayload clears the value of the "decision_payload" field.
func (u *FlowExecutionUpsertBulk) ClearDecisionPayload() *FlowExecutionUpsertBulk {
	return u.Update(func(s *FlowExecutionUpsert) {
		s.ClearDecisionPayload()
	})
}

// Exec executes the query.
func (u *FlowExecutionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FlowExecutionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlowExecutionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlowExecutionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
