// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/multisigconfig"
	"github.com/lightsparkdev/spark/so/ent/multisigmember"
)

// MultisigConfigCreate is the builder for creating a MultisigConfig entity.
type MultisigConfigCreate struct {
	config
	mutation *MultisigConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (mcc *MultisigConfigCreate) SetCreateTime(t time.Time) *MultisigConfigCreate {
	mcc.mutation.SetCreateTime(t)
	return mcc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (mcc *MultisigConfigCreate) SetNillableCreateTime(t *time.Time) *MultisigConfigCreate {
	if t != nil {
		mcc.SetCreateTime(*t)
	}
	return mcc
}

// SetUpdateTime sets the "update_time" field.
func (mcc *MultisigConfigCreate) SetUpdateTime(t time.Time) *MultisigConfigCreate {
	mcc.mutation.SetUpdateTime(t)
	return mcc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (mcc *MultisigConfigCreate) SetNillableUpdateTime(t *time.Time) *MultisigConfigCreate {
	if t != nil {
		mcc.SetUpdateTime(*t)
	}
	return mcc
}

// SetMultisigIdentifier sets the "multisig_identifier" field.
func (mcc *MultisigConfigCreate) SetMultisigIdentifier(b []byte) *MultisigConfigCreate {
	mcc.mutation.SetMultisigIdentifier(b)
	return mcc
}

// SetNumSignersThreshold sets the "num_signers_threshold" field.
func (mcc *MultisigConfigCreate) SetNumSignersThreshold(u uint32) *MultisigConfigCreate {
	mcc.mutation.SetNumSignersThreshold(u)
	return mcc
}

// SetNumSignersTotal sets the "num_signers_total" field.
func (mcc *MultisigConfigCreate) SetNumSignersTotal(u uint32) *MultisigConfigCreate {
	mcc.mutation.SetNumSignersTotal(u)
	return mcc
}

// SetID sets the "id" field.
func (mcc *MultisigConfigCreate) SetID(u uuid.UUID) *MultisigConfigCreate {
	mcc.mutation.SetID(u)
	return mcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mcc *MultisigConfigCreate) SetNillableID(u *uuid.UUID) *MultisigConfigCreate {
	if u != nil {
		mcc.SetID(*u)
	}
	return mcc
}

// AddMemberIDs adds the "members" edge to the MultisigMember entity by IDs.
func (mcc *MultisigConfigCreate) AddMemberIDs(ids ...uuid.UUID) *MultisigConfigCreate {
	mcc.mutation.AddMemberIDs(ids...)
	return mcc
}

// AddMembers adds the "members" edges to the MultisigMember entity.
func (mcc *MultisigConfigCreate) AddMembers(m ...*MultisigMember) *MultisigConfigCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mcc.AddMemberIDs(ids...)
}

// Mutation returns the MultisigConfigMutation object of the builder.
func (mcc *MultisigConfigCreate) Mutation() *MultisigConfigMutation {
	return mcc.mutation
}

// Save creates the MultisigConfig in the database.
func (mcc *MultisigConfigCreate) Save(ctx context.Context) (*MultisigConfig, error) {
	if err := mcc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, mcc.sqlSave, mcc.mutation, mcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mcc *MultisigConfigCreate) SaveX(ctx context.Context) *MultisigConfig {
	v, err := mcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcc *MultisigConfigCreate) Exec(ctx context.Context) error {
	_, err := mcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcc *MultisigConfigCreate) ExecX(ctx context.Context) {
	if err := mcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mcc *MultisigConfigCreate) defaults() error {
	if _, ok := mcc.mutation.CreateTime(); !ok {
		if multisigconfig.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized multisigconfig.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := multisigconfig.DefaultCreateTime()
		mcc.mutation.SetCreateTime(v)
	}
	if _, ok := mcc.mutation.UpdateTime(); !ok {
		if multisigconfig.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized multisigconfig.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := multisigconfig.DefaultUpdateTime()
		mcc.mutation.SetUpdateTime(v)
	}
	if _, ok := mcc.mutation.ID(); !ok {
		if multisigconfig.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized multisigconfig.DefaultID (forgotten import ent/runtime?)")
		}
		v := multisigconfig.DefaultID()
		mcc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mcc *MultisigConfigCreate) check() error {
	if _, ok := mcc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "MultisigConfig.create_time"`)}
	}
	if _, ok := mcc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "MultisigConfig.update_time"`)}
	}
	if _, ok := mcc.mutation.MultisigIdentifier(); !ok {
		return &ValidationError{Name: "multisig_identifier", err: errors.New(`ent: missing required field "MultisigConfig.multisig_identifier"`)}
	}
	if v, ok := mcc.mutation.MultisigIdentifier(); ok {
		if err := multisigconfig.MultisigIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "multisig_identifier", err: fmt.Errorf(`ent: validator failed for field "MultisigConfig.multisig_identifier": %w`, err)}
		}
	}
	if _, ok := mcc.mutation.NumSignersThreshold(); !ok {
		return &ValidationError{Name: "num_signers_threshold", err: errors.New(`ent: missing required field "MultisigConfig.num_signers_threshold"`)}
	}
	if v, ok := mcc.mutation.NumSignersThreshold(); ok {
		if err := multisigconfig.NumSignersThresholdValidator(v); err != nil {
			return &ValidationError{Name: "num_signers_threshold", err: fmt.Errorf(`ent: validator failed for field "MultisigConfig.num_signers_threshold": %w`, err)}
		}
	}
	if _, ok := mcc.mutation.NumSignersTotal(); !ok {
		return &ValidationError{Name: "num_signers_total", err: errors.New(`ent: missing required field "MultisigConfig.num_signers_total"`)}
	}
	if v, ok := mcc.mutation.NumSignersTotal(); ok {
		if err := multisigconfig.NumSignersTotalValidator(v); err != nil {
			return &ValidationError{Name: "num_signers_total", err: fmt.Errorf(`ent: validator failed for field "MultisigConfig.num_signers_total": %w`, err)}
		}
	}
	return nil
}

func (mcc *MultisigConfigCreate) sqlSave(ctx context.Context) (*MultisigConfig, error) {
	if err := mcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mcc.mutation.id = &_node.ID
	mcc.mutation.done = true
	return _node, nil
}

func (mcc *MultisigConfigCreate) createSpec() (*MultisigConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &MultisigConfig{config: mcc.config}
		_spec = sqlgraph.NewCreateSpec(multisigconfig.Table, sqlgraph.NewFieldSpec(multisigconfig.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = mcc.conflict
	if id, ok := mcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mcc.mutation.CreateTime(); ok {
		_spec.SetField(multisigconfig.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := mcc.mutation.UpdateTime(); ok {
		_spec.SetField(multisigconfig.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := mcc.mutation.MultisigIdentifier(); ok {
		_spec.SetField(multisigconfig.FieldMultisigIdentifier, field.TypeBytes, value)
		_node.MultisigIdentifier = value
	}
	if value, ok := mcc.mutation.NumSignersThreshold(); ok {
		_spec.SetField(multisigconfig.FieldNumSignersThreshold, field.TypeUint32, value)
		_node.NumSignersThreshold = value
	}
	if value, ok := mcc.mutation.NumSignersTotal(); ok {
		_spec.SetField(multisigconfig.FieldNumSignersTotal, field.TypeUint32, value)
		_node.NumSignersTotal = value
	}
	if nodes := mcc.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   multisigconfig.MembersTable,
			Columns: []string{multisigconfig.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(multisigmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MultisigConfig.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MultisigConfigUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (mcc *MultisigConfigCreate) OnConflict(opts ...sql.ConflictOption) *MultisigConfigUpsertOne {
	mcc.conflict = opts
	return &MultisigConfigUpsertOne{
		create: mcc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MultisigConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mcc *MultisigConfigCreate) OnConflictColumns(columns ...string) *MultisigConfigUpsertOne {
	mcc.conflict = append(mcc.conflict, sql.ConflictColumns(columns...))
	return &MultisigConfigUpsertOne{
		create: mcc,
	}
}

type (
	// MultisigConfigUpsertOne is the builder for "upsert"-ing
	//  one MultisigConfig node.
	MultisigConfigUpsertOne struct {
		create *MultisigConfigCreate
	}

	// MultisigConfigUpsert is the "OnConflict" setter.
	MultisigConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *MultisigConfigUpsert) SetUpdateTime(v time.Time) *MultisigConfigUpsert {
	u.Set(multisigconfig.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *MultisigConfigUpsert) UpdateUpdateTime() *MultisigConfigUpsert {
	u.SetExcluded(multisigconfig.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MultisigConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(multisigconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MultisigConfigUpsertOne) UpdateNewValues() *MultisigConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(multisigconfig.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(multisigconfig.FieldCreateTime)
		}
		if _, exists := u.create.mutation.MultisigIdentifier(); exists {
			s.SetIgnore(multisigconfig.FieldMultisigIdentifier)
		}
		if _, exists := u.create.mutation.NumSignersThreshold(); exists {
			s.SetIgnore(multisigconfig.FieldNumSignersThreshold)
		}
		if _, exists := u.create.mutation.NumSignersTotal(); exists {
			s.SetIgnore(multisigconfig.FieldNumSignersTotal)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MultisigConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MultisigConfigUpsertOne) Ignore() *MultisigConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MultisigConfigUpsertOne) DoNothing() *MultisigConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MultisigConfigCreate.OnConflict
// documentation for more info.
func (u *MultisigConfigUpsertOne) Update(set func(*MultisigConfigUpsert)) *MultisigConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MultisigConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *MultisigConfigUpsertOne) SetUpdateTime(v time.Time) *MultisigConfigUpsertOne {
	return u.Update(func(s *MultisigConfigUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *MultisigConfigUpsertOne) UpdateUpdateTime() *MultisigConfigUpsertOne {
	return u.Update(func(s *MultisigConfigUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *MultisigConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MultisigConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MultisigConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MultisigConfigUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MultisigConfigUpsertOne.ID is not supported by MySQL driver. Use MultisigConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MultisigConfigUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MultisigConfigCreateBulk is the builder for creating many MultisigConfig entities in bulk.
type MultisigConfigCreateBulk struct {
	config
	err      error
	builders []*MultisigConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the MultisigConfig entities in the database.
func (mccb *MultisigConfigCreateBulk) Save(ctx context.Context) ([]*MultisigConfig, error) {
	if mccb.err != nil {
		return nil, mccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mccb.builders))
	nodes := make([]*MultisigConfig, len(mccb.builders))
	mutators := make([]Mutator, len(mccb.builders))
	for i := range mccb.builders {
		func(i int, root context.Context) {
			builder := mccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MultisigConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mccb *MultisigConfigCreateBulk) SaveX(ctx context.Context) []*MultisigConfig {
	v, err := mccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mccb *MultisigConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := mccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mccb *MultisigConfigCreateBulk) ExecX(ctx context.Context) {
	if err := mccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MultisigConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MultisigConfigUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (mccb *MultisigConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *MultisigConfigUpsertBulk {
	mccb.conflict = opts
	return &MultisigConfigUpsertBulk{
		create: mccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MultisigConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mccb *MultisigConfigCreateBulk) OnConflictColumns(columns ...string) *MultisigConfigUpsertBulk {
	mccb.conflict = append(mccb.conflict, sql.ConflictColumns(columns...))
	return &MultisigConfigUpsertBulk{
		create: mccb,
	}
}

// MultisigConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of MultisigConfig nodes.
type MultisigConfigUpsertBulk struct {
	create *MultisigConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MultisigConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(multisigconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MultisigConfigUpsertBulk) UpdateNewValues() *MultisigConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(multisigconfig.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(multisigconfig.FieldCreateTime)
			}
			if _, exists := b.mutation.MultisigIdentifier(); exists {
				s.SetIgnore(multisigconfig.FieldMultisigIdentifier)
			}
			if _, exists := b.mutation.NumSignersThreshold(); exists {
				s.SetIgnore(multisigconfig.FieldNumSignersThreshold)
			}
			if _, exists := b.mutation.NumSignersTotal(); exists {
				s.SetIgnore(multisigconfig.FieldNumSignersTotal)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MultisigConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MultisigConfigUpsertBulk) Ignore() *MultisigConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MultisigConfigUpsertBulk) DoNothing() *MultisigConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MultisigConfigCreateBulk.OnConflict
// documentation for more info.
func (u *MultisigConfigUpsertBulk) Update(set func(*MultisigConfigUpsert)) *MultisigConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MultisigConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *MultisigConfigUpsertBulk) SetUpdateTime(v time.Time) *MultisigConfigUpsertBulk {
	return u.Update(func(s *MultisigConfigUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *MultisigConfigUpsertBulk) UpdateUpdateTime() *MultisigConfigUpsertBulk {
	return u.Update(func(s *MultisigConfigUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *MultisigConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MultisigConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MultisigConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MultisigConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
