// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/multisigmember"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// MultisigMemberUpdate is the builder for updating MultisigMember entities.
type MultisigMemberUpdate struct {
	config
	hooks     []Hook
	mutation  *MultisigMemberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MultisigMemberUpdate builder.
func (mmu *MultisigMemberUpdate) Where(ps ...predicate.MultisigMember) *MultisigMemberUpdate {
	mmu.mutation.Where(ps...)
	return mmu
}

// SetUpdateTime sets the "update_time" field.
func (mmu *MultisigMemberUpdate) SetUpdateTime(t time.Time) *MultisigMemberUpdate {
	mmu.mutation.SetUpdateTime(t)
	return mmu
}

// Mutation returns the MultisigMemberMutation object of the builder.
func (mmu *MultisigMemberUpdate) Mutation() *MultisigMemberMutation {
	return mmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mmu *MultisigMemberUpdate) Save(ctx context.Context) (int, error) {
	if err := mmu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, mmu.sqlSave, mmu.mutation, mmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mmu *MultisigMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := mmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mmu *MultisigMemberUpdate) Exec(ctx context.Context) error {
	_, err := mmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmu *MultisigMemberUpdate) ExecX(ctx context.Context) {
	if err := mmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mmu *MultisigMemberUpdate) defaults() error {
	if _, ok := mmu.mutation.UpdateTime(); !ok {
		if multisigmember.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized multisigmember.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := multisigmember.UpdateDefaultUpdateTime()
		mmu.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mmu *MultisigMemberUpdate) check() error {
	if mmu.mutation.ConfigCleared() && len(mmu.mutation.ConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MultisigMember.config"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (mmu *MultisigMemberUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MultisigMemberUpdate {
	mmu.modifiers = append(mmu.modifiers, modifiers...)
	return mmu
}

func (mmu *MultisigMemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mmu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(multisigmember.Table, multisigmember.Columns, sqlgraph.NewFieldSpec(multisigmember.FieldID, field.TypeUUID))
	if ps := mmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mmu.mutation.UpdateTime(); ok {
		_spec.SetField(multisigmember.FieldUpdateTime, field.TypeTime, value)
	}
	_spec.AddModifiers(mmu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, mmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{multisigmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mmu.mutation.done = true
	return n, nil
}

// MultisigMemberUpdateOne is the builder for updating a single MultisigMember entity.
type MultisigMemberUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MultisigMemberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (mmuo *MultisigMemberUpdateOne) SetUpdateTime(t time.Time) *MultisigMemberUpdateOne {
	mmuo.mutation.SetUpdateTime(t)
	return mmuo
}

// Mutation returns the MultisigMemberMutation object of the builder.
func (mmuo *MultisigMemberUpdateOne) Mutation() *MultisigMemberMutation {
	return mmuo.mutation
}

// Where appends a list predicates to the MultisigMemberUpdate builder.
func (mmuo *MultisigMemberUpdateOne) Where(ps ...predicate.MultisigMember) *MultisigMemberUpdateOne {
	mmuo.mutation.Where(ps...)
	return mmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mmuo *MultisigMemberUpdateOne) Select(field string, fields ...string) *MultisigMemberUpdateOne {
	mmuo.fields = append([]string{field}, fields...)
	return mmuo
}

// Save executes the query and returns the updated MultisigMember entity.
func (mmuo *MultisigMemberUpdateOne) Save(ctx context.Context) (*MultisigMember, error) {
	if err := mmuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, mmuo.sqlSave, mmuo.mutation, mmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mmuo *MultisigMemberUpdateOne) SaveX(ctx context.Context) *MultisigMember {
	node, err := mmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mmuo *MultisigMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := mmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmuo *MultisigMemberUpdateOne) ExecX(ctx context.Context) {
	if err := mmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mmuo *MultisigMemberUpdateOne) defaults() error {
	if _, ok := mmuo.mutation.UpdateTime(); !ok {
		if multisigmember.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized multisigmember.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := multisigmember.UpdateDefaultUpdateTime()
		mmuo.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mmuo *MultisigMemberUpdateOne) check() error {
	if mmuo.mutation.ConfigCleared() && len(mmuo.mutation.ConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MultisigMember.config"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (mmuo *MultisigMemberUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MultisigMemberUpdateOne {
	mmuo.modifiers = append(mmuo.modifiers, modifiers...)
	return mmuo
}

func (mmuo *MultisigMemberUpdateOne) sqlSave(ctx context.Context) (_node *MultisigMember, err error) {
	if err := mmuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(multisigmember.Table, multisigmember.Columns, sqlgraph.NewFieldSpec(multisigmember.FieldID, field.TypeUUID))
	id, ok := mmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MultisigMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, multisigmember.FieldID)
		for _, f := range fields {
			if !multisigmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != multisigmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mmuo.mutation.UpdateTime(); ok {
		_spec.SetField(multisigmember.FieldUpdateTime, field.TypeTime, value)
	}
	_spec.AddModifiers(mmuo.modifiers...)
	_node = &MultisigMember{config: mmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{multisigmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mmuo.mutation.done = true
	return _node, nil
}
