// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/multisigconfig"
	"github.com/lightsparkdev/spark/so/ent/multisigmember"
)

// MultisigMember is the model entity for the MultisigMember schema.
type MultisigMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// 33-byte compressed public key of this multisig participant
	PublicKey keys.Public `json:"public_key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MultisigMemberQuery when eager-loading is set.
	Edges                   MultisigMemberEdges `json:"edges"`
	multisig_config_members *uuid.UUID
	selectValues            sql.SelectValues
}

// MultisigMemberEdges holds the relations/edges for other nodes in the graph.
type MultisigMemberEdges struct {
	// Config holds the value of the config edge.
	Config *MultisigConfig `json:"config,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConfigOrErr returns the Config value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MultisigMemberEdges) ConfigOrErr() (*MultisigConfig, error) {
	if e.Config != nil {
		return e.Config, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: multisigconfig.Label}
	}
	return nil, &NotLoadedError{edge: "config"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MultisigMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case multisigmember.FieldPublicKey:
			values[i] = new(keys.Public)
		case multisigmember.FieldCreateTime, multisigmember.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case multisigmember.FieldID:
			values[i] = new(uuid.UUID)
		case multisigmember.ForeignKeys[0]: // multisig_config_members
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MultisigMember fields.
func (mm *MultisigMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case multisigmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mm.ID = *value
			}
		case multisigmember.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				mm.CreateTime = value.Time
			}
		case multisigmember.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				mm.UpdateTime = value.Time
			}
		case multisigmember.FieldPublicKey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				mm.PublicKey = *value
			}
		case multisigmember.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field multisig_config_members", values[i])
			} else if value.Valid {
				mm.multisig_config_members = new(uuid.UUID)
				*mm.multisig_config_members = *value.S.(*uuid.UUID)
			}
		default:
			mm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MultisigMember.
// This includes values selected through modifiers, order, etc.
func (mm *MultisigMember) Value(name string) (ent.Value, error) {
	return mm.selectValues.Get(name)
}

// QueryConfig queries the "config" edge of the MultisigMember entity.
func (mm *MultisigMember) QueryConfig() *MultisigConfigQuery {
	return NewMultisigMemberClient(mm.config).QueryConfig(mm)
}

// Update returns a builder for updating this MultisigMember.
// Note that you need to call MultisigMember.Unwrap() before calling this method if this MultisigMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (mm *MultisigMember) Update() *MultisigMemberUpdateOne {
	return NewMultisigMemberClient(mm.config).UpdateOne(mm)
}

// Unwrap unwraps the MultisigMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mm *MultisigMember) Unwrap() *MultisigMember {
	_tx, ok := mm.config.driver.(*txDriver)
	if !ok {
		panic("ent: MultisigMember is not a transactional entity")
	}
	mm.config.driver = _tx.drv
	return mm
}

// String implements the fmt.Stringer.
func (mm *MultisigMember) String() string {
	var builder strings.Builder
	builder.WriteString("MultisigMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mm.ID))
	builder.WriteString("create_time=")
	builder.WriteString(mm.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(mm.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", mm.PublicKey))
	builder.WriteByte(')')
	return builder.String()
}

// MultisigMembers is a parsable slice of MultisigMember.
type MultisigMembers []*MultisigMember
