// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/multisigconfig"
	"github.com/lightsparkdev/spark/so/ent/multisigmember"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// MultisigConfigQuery is the builder for querying MultisigConfig entities.
type MultisigConfigQuery struct {
	config
	ctx         *QueryContext
	order       []multisigconfig.OrderOption
	inters      []Interceptor
	predicates  []predicate.MultisigConfig
	withMembers *MultisigMemberQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MultisigConfigQuery builder.
func (mcq *MultisigConfigQuery) Where(ps ...predicate.MultisigConfig) *MultisigConfigQuery {
	mcq.predicates = append(mcq.predicates, ps...)
	return mcq
}

// Limit the number of records to be returned by this query.
func (mcq *MultisigConfigQuery) Limit(limit int) *MultisigConfigQuery {
	mcq.ctx.Limit = &limit
	return mcq
}

// Offset to start from.
func (mcq *MultisigConfigQuery) Offset(offset int) *MultisigConfigQuery {
	mcq.ctx.Offset = &offset
	return mcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mcq *MultisigConfigQuery) Unique(unique bool) *MultisigConfigQuery {
	mcq.ctx.Unique = &unique
	return mcq
}

// Order specifies how the records should be ordered.
func (mcq *MultisigConfigQuery) Order(o ...multisigconfig.OrderOption) *MultisigConfigQuery {
	mcq.order = append(mcq.order, o...)
	return mcq
}

// QueryMembers chains the current query on the "members" edge.
func (mcq *MultisigConfigQuery) QueryMembers() *MultisigMemberQuery {
	query := (&MultisigMemberClient{config: mcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(multisigconfig.Table, multisigconfig.FieldID, selector),
			sqlgraph.To(multisigmember.Table, multisigmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, multisigconfig.MembersTable, multisigconfig.MembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(mcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MultisigConfig entity from the query.
// Returns a *NotFoundError when no MultisigConfig was found.
func (mcq *MultisigConfigQuery) First(ctx context.Context) (*MultisigConfig, error) {
	nodes, err := mcq.Limit(1).All(setContextOp(ctx, mcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{multisigconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mcq *MultisigConfigQuery) FirstX(ctx context.Context) *MultisigConfig {
	node, err := mcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MultisigConfig ID from the query.
// Returns a *NotFoundError when no MultisigConfig ID was found.
func (mcq *MultisigConfigQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mcq.Limit(1).IDs(setContextOp(ctx, mcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{multisigconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mcq *MultisigConfigQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MultisigConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MultisigConfig entity is found.
// Returns a *NotFoundError when no MultisigConfig entities are found.
func (mcq *MultisigConfigQuery) Only(ctx context.Context) (*MultisigConfig, error) {
	nodes, err := mcq.Limit(2).All(setContextOp(ctx, mcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{multisigconfig.Label}
	default:
		return nil, &NotSingularError{multisigconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mcq *MultisigConfigQuery) OnlyX(ctx context.Context) *MultisigConfig {
	node, err := mcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MultisigConfig ID in the query.
// Returns a *NotSingularError when more than one MultisigConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (mcq *MultisigConfigQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mcq.Limit(2).IDs(setContextOp(ctx, mcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{multisigconfig.Label}
	default:
		err = &NotSingularError{multisigconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mcq *MultisigConfigQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MultisigConfigs.
func (mcq *MultisigConfigQuery) All(ctx context.Context) ([]*MultisigConfig, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryAll)
	if err := mcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MultisigConfig, *MultisigConfigQuery]()
	return withInterceptors[[]*MultisigConfig](ctx, mcq, qr, mcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mcq *MultisigConfigQuery) AllX(ctx context.Context) []*MultisigConfig {
	nodes, err := mcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MultisigConfig IDs.
func (mcq *MultisigConfigQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if mcq.ctx.Unique == nil && mcq.path != nil {
		mcq.Unique(true)
	}
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryIDs)
	if err = mcq.Select(multisigconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mcq *MultisigConfigQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mcq *MultisigConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryCount)
	if err := mcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mcq, querierCount[*MultisigConfigQuery](), mcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mcq *MultisigConfigQuery) CountX(ctx context.Context) int {
	count, err := mcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mcq *MultisigConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryExist)
	switch _, err := mcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mcq *MultisigConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := mcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MultisigConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mcq *MultisigConfigQuery) Clone() *MultisigConfigQuery {
	if mcq == nil {
		return nil
	}
	return &MultisigConfigQuery{
		config:      mcq.config,
		ctx:         mcq.ctx.Clone(),
		order:       append([]multisigconfig.OrderOption{}, mcq.order...),
		inters:      append([]Interceptor{}, mcq.inters...),
		predicates:  append([]predicate.MultisigConfig{}, mcq.predicates...),
		withMembers: mcq.withMembers.Clone(),
		// clone intermediate query.
		sql:       mcq.sql.Clone(),
		path:      mcq.path,
		modifiers: append([]func(*sql.Selector){}, mcq.modifiers...),
	}
}

// WithMembers tells the query-builder to eager-load the nodes that are connected to
// the "members" edge. The optional arguments are used to configure the query builder of the edge.
func (mcq *MultisigConfigQuery) WithMembers(opts ...func(*MultisigMemberQuery)) *MultisigConfigQuery {
	query := (&MultisigMemberClient{config: mcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mcq.withMembers = query
	return mcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MultisigConfig.Query().
//		GroupBy(multisigconfig.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mcq *MultisigConfigQuery) GroupBy(field string, fields ...string) *MultisigConfigGroupBy {
	mcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MultisigConfigGroupBy{build: mcq}
	grbuild.flds = &mcq.ctx.Fields
	grbuild.label = multisigconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.MultisigConfig.Query().
//		Select(multisigconfig.FieldCreateTime).
//		Scan(ctx, &v)
func (mcq *MultisigConfigQuery) Select(fields ...string) *MultisigConfigSelect {
	mcq.ctx.Fields = append(mcq.ctx.Fields, fields...)
	sbuild := &MultisigConfigSelect{MultisigConfigQuery: mcq}
	sbuild.label = multisigconfig.Label
	sbuild.flds, sbuild.scan = &mcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MultisigConfigSelect configured with the given aggregations.
func (mcq *MultisigConfigQuery) Aggregate(fns ...AggregateFunc) *MultisigConfigSelect {
	return mcq.Select().Aggregate(fns...)
}

func (mcq *MultisigConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mcq); err != nil {
				return err
			}
		}
	}
	for _, f := range mcq.ctx.Fields {
		if !multisigconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mcq.path != nil {
		prev, err := mcq.path(ctx)
		if err != nil {
			return err
		}
		mcq.sql = prev
	}
	return nil
}

func (mcq *MultisigConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MultisigConfig, error) {
	var (
		nodes       = []*MultisigConfig{}
		_spec       = mcq.querySpec()
		loadedTypes = [1]bool{
			mcq.withMembers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MultisigConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MultisigConfig{config: mcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(mcq.modifiers) > 0 {
		_spec.Modifiers = mcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mcq.withMembers; query != nil {
		if err := mcq.loadMembers(ctx, query, nodes,
			func(n *MultisigConfig) { n.Edges.Members = []*MultisigMember{} },
			func(n *MultisigConfig, e *MultisigMember) { n.Edges.Members = append(n.Edges.Members, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mcq *MultisigConfigQuery) loadMembers(ctx context.Context, query *MultisigMemberQuery, nodes []*MultisigConfig, init func(*MultisigConfig), assign func(*MultisigConfig, *MultisigMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*MultisigConfig)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MultisigMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(multisigconfig.MembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.multisig_config_members
		if fk == nil {
			return fmt.Errorf(`foreign-key "multisig_config_members" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "multisig_config_members" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mcq *MultisigConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mcq.querySpec()
	if len(mcq.modifiers) > 0 {
		_spec.Modifiers = mcq.modifiers
	}
	_spec.Node.Columns = mcq.ctx.Fields
	if len(mcq.ctx.Fields) > 0 {
		_spec.Unique = mcq.ctx.Unique != nil && *mcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mcq.driver, _spec)
}

func (mcq *MultisigConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(multisigconfig.Table, multisigconfig.Columns, sqlgraph.NewFieldSpec(multisigconfig.FieldID, field.TypeUUID))
	_spec.From = mcq.sql
	if unique := mcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mcq.path != nil {
		_spec.Unique = true
	}
	if fields := mcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, multisigconfig.FieldID)
		for i := range fields {
			if fields[i] != multisigconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mcq *MultisigConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mcq.driver.Dialect())
	t1 := builder.Table(multisigconfig.Table)
	columns := mcq.ctx.Fields
	if len(columns) == 0 {
		columns = multisigconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mcq.sql != nil {
		selector = mcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mcq.ctx.Unique != nil && *mcq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range mcq.modifiers {
		m(selector)
	}
	for _, p := range mcq.predicates {
		p(selector)
	}
	for _, p := range mcq.order {
		p(selector)
	}
	if offset := mcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (mcq *MultisigConfigQuery) ForUpdate(opts ...sql.LockOption) *MultisigConfigQuery {
	if mcq.driver.Dialect() == dialect.Postgres {
		mcq.Unique(false)
	}
	mcq.modifiers = append(mcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return mcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (mcq *MultisigConfigQuery) ForShare(opts ...sql.LockOption) *MultisigConfigQuery {
	if mcq.driver.Dialect() == dialect.Postgres {
		mcq.Unique(false)
	}
	mcq.modifiers = append(mcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return mcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mcq *MultisigConfigQuery) Modify(modifiers ...func(s *sql.Selector)) *MultisigConfigSelect {
	mcq.modifiers = append(mcq.modifiers, modifiers...)
	return mcq.Select()
}

// MultisigConfigGroupBy is the group-by builder for MultisigConfig entities.
type MultisigConfigGroupBy struct {
	selector
	build *MultisigConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mcgb *MultisigConfigGroupBy) Aggregate(fns ...AggregateFunc) *MultisigConfigGroupBy {
	mcgb.fns = append(mcgb.fns, fns...)
	return mcgb
}

// Scan applies the selector query and scans the result into the given value.
func (mcgb *MultisigConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcgb.build.ctx, ent.OpQueryGroupBy)
	if err := mcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MultisigConfigQuery, *MultisigConfigGroupBy](ctx, mcgb.build, mcgb, mcgb.build.inters, v)
}

func (mcgb *MultisigConfigGroupBy) sqlScan(ctx context.Context, root *MultisigConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mcgb.fns))
	for _, fn := range mcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mcgb.flds)+len(mcgb.fns))
		for _, f := range *mcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MultisigConfigSelect is the builder for selecting fields of MultisigConfig entities.
type MultisigConfigSelect struct {
	*MultisigConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mcs *MultisigConfigSelect) Aggregate(fns ...AggregateFunc) *MultisigConfigSelect {
	mcs.fns = append(mcs.fns, fns...)
	return mcs
}

// Scan applies the selector query and scans the result into the given value.
func (mcs *MultisigConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcs.ctx, ent.OpQuerySelect)
	if err := mcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MultisigConfigQuery, *MultisigConfigSelect](ctx, mcs.MultisigConfigQuery, mcs, mcs.inters, v)
}

func (mcs *MultisigConfigSelect) sqlScan(ctx context.Context, root *MultisigConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mcs.fns))
	for _, fn := range mcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mcs *MultisigConfigSelect) Modify(modifiers ...func(s *sql.Selector)) *MultisigConfigSelect {
	mcs.modifiers = append(mcs.modifiers, modifiers...)
	return mcs
}
