// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/multisigconfig"
	"github.com/lightsparkdev/spark/so/ent/multisigmember"
)

// MultisigMemberCreate is the builder for creating a MultisigMember entity.
type MultisigMemberCreate struct {
	config
	mutation *MultisigMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (mmc *MultisigMemberCreate) SetCreateTime(t time.Time) *MultisigMemberCreate {
	mmc.mutation.SetCreateTime(t)
	return mmc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (mmc *MultisigMemberCreate) SetNillableCreateTime(t *time.Time) *MultisigMemberCreate {
	if t != nil {
		mmc.SetCreateTime(*t)
	}
	return mmc
}

// SetUpdateTime sets the "update_time" field.
func (mmc *MultisigMemberCreate) SetUpdateTime(t time.Time) *MultisigMemberCreate {
	mmc.mutation.SetUpdateTime(t)
	return mmc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (mmc *MultisigMemberCreate) SetNillableUpdateTime(t *time.Time) *MultisigMemberCreate {
	if t != nil {
		mmc.SetUpdateTime(*t)
	}
	return mmc
}

// SetPublicKey sets the "public_key" field.
func (mmc *MultisigMemberCreate) SetPublicKey(k keys.Public) *MultisigMemberCreate {
	mmc.mutation.SetPublicKey(k)
	return mmc
}

// SetID sets the "id" field.
func (mmc *MultisigMemberCreate) SetID(u uuid.UUID) *MultisigMemberCreate {
	mmc.mutation.SetID(u)
	return mmc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mmc *MultisigMemberCreate) SetNillableID(u *uuid.UUID) *MultisigMemberCreate {
	if u != nil {
		mmc.SetID(*u)
	}
	return mmc
}

// SetConfigID sets the "config" edge to the MultisigConfig entity by ID.
func (mmc *MultisigMemberCreate) SetConfigID(id uuid.UUID) *MultisigMemberCreate {
	mmc.mutation.SetConfigID(id)
	return mmc
}

// SetConfig sets the "config" edge to the MultisigConfig entity.
func (mmc *MultisigMemberCreate) SetConfig(m *MultisigConfig) *MultisigMemberCreate {
	return mmc.SetConfigID(m.ID)
}

// Mutation returns the MultisigMemberMutation object of the builder.
func (mmc *MultisigMemberCreate) Mutation() *MultisigMemberMutation {
	return mmc.mutation
}

// Save creates the MultisigMember in the database.
func (mmc *MultisigMemberCreate) Save(ctx context.Context) (*MultisigMember, error) {
	if err := mmc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, mmc.sqlSave, mmc.mutation, mmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mmc *MultisigMemberCreate) SaveX(ctx context.Context) *MultisigMember {
	v, err := mmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mmc *MultisigMemberCreate) Exec(ctx context.Context) error {
	_, err := mmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmc *MultisigMemberCreate) ExecX(ctx context.Context) {
	if err := mmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mmc *MultisigMemberCreate) defaults() error {
	if _, ok := mmc.mutation.CreateTime(); !ok {
		if multisigmember.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized multisigmember.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := multisigmember.DefaultCreateTime()
		mmc.mutation.SetCreateTime(v)
	}
	if _, ok := mmc.mutation.UpdateTime(); !ok {
		if multisigmember.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized multisigmember.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := multisigmember.DefaultUpdateTime()
		mmc.mutation.SetUpdateTime(v)
	}
	if _, ok := mmc.mutation.ID(); !ok {
		if multisigmember.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized multisigmember.DefaultID (forgotten import ent/runtime?)")
		}
		v := multisigmember.DefaultID()
		mmc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mmc *MultisigMemberCreate) check() error {
	if _, ok := mmc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "MultisigMember.create_time"`)}
	}
	if _, ok := mmc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "MultisigMember.update_time"`)}
	}
	if _, ok := mmc.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "MultisigMember.public_key"`)}
	}
	if len(mmc.mutation.ConfigIDs()) == 0 {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required edge "MultisigMember.config"`)}
	}
	return nil
}

func (mmc *MultisigMemberCreate) sqlSave(ctx context.Context) (*MultisigMember, error) {
	if err := mmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mmc.mutation.id = &_node.ID
	mmc.mutation.done = true
	return _node, nil
}

func (mmc *MultisigMemberCreate) createSpec() (*MultisigMember, *sqlgraph.CreateSpec) {
	var (
		_node = &MultisigMember{config: mmc.config}
		_spec = sqlgraph.NewCreateSpec(multisigmember.Table, sqlgraph.NewFieldSpec(multisigmember.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = mmc.conflict
	if id, ok := mmc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mmc.mutation.CreateTime(); ok {
		_spec.SetField(multisigmember.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := mmc.mutation.UpdateTime(); ok {
		_spec.SetField(multisigmember.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := mmc.mutation.PublicKey(); ok {
		_spec.SetField(multisigmember.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	if nodes := mmc.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   multisigmember.ConfigTable,
			Columns: []string{multisigmember.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(multisigconfig.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.multisig_config_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MultisigMember.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MultisigMemberUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (mmc *MultisigMemberCreate) OnConflict(opts ...sql.ConflictOption) *MultisigMemberUpsertOne {
	mmc.conflict = opts
	return &MultisigMemberUpsertOne{
		create: mmc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MultisigMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mmc *MultisigMemberCreate) OnConflictColumns(columns ...string) *MultisigMemberUpsertOne {
	mmc.conflict = append(mmc.conflict, sql.ConflictColumns(columns...))
	return &MultisigMemberUpsertOne{
		create: mmc,
	}
}

type (
	// MultisigMemberUpsertOne is the builder for "upsert"-ing
	//  one MultisigMember node.
	MultisigMemberUpsertOne struct {
		create *MultisigMemberCreate
	}

	// MultisigMemberUpsert is the "OnConflict" setter.
	MultisigMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *MultisigMemberUpsert) SetUpdateTime(v time.Time) *MultisigMemberUpsert {
	u.Set(multisigmember.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *MultisigMemberUpsert) UpdateUpdateTime() *MultisigMemberUpsert {
	u.SetExcluded(multisigmember.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MultisigMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(multisigmember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MultisigMemberUpsertOne) UpdateNewValues() *MultisigMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(multisigmember.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(multisigmember.FieldCreateTime)
		}
		if _, exists := u.create.mutation.PublicKey(); exists {
			s.SetIgnore(multisigmember.FieldPublicKey)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MultisigMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MultisigMemberUpsertOne) Ignore() *MultisigMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MultisigMemberUpsertOne) DoNothing() *MultisigMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MultisigMemberCreate.OnConflict
// documentation for more info.
func (u *MultisigMemberUpsertOne) Update(set func(*MultisigMemberUpsert)) *MultisigMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MultisigMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *MultisigMemberUpsertOne) SetUpdateTime(v time.Time) *MultisigMemberUpsertOne {
	return u.Update(func(s *MultisigMemberUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *MultisigMemberUpsertOne) UpdateUpdateTime() *MultisigMemberUpsertOne {
	return u.Update(func(s *MultisigMemberUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *MultisigMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MultisigMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MultisigMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MultisigMemberUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MultisigMemberUpsertOne.ID is not supported by MySQL driver. Use MultisigMemberUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MultisigMemberUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MultisigMemberCreateBulk is the builder for creating many MultisigMember entities in bulk.
type MultisigMemberCreateBulk struct {
	config
	err      error
	builders []*MultisigMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the MultisigMember entities in the database.
func (mmcb *MultisigMemberCreateBulk) Save(ctx context.Context) ([]*MultisigMember, error) {
	if mmcb.err != nil {
		return nil, mmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mmcb.builders))
	nodes := make([]*MultisigMember, len(mmcb.builders))
	mutators := make([]Mutator, len(mmcb.builders))
	for i := range mmcb.builders {
		func(i int, root context.Context) {
			builder := mmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MultisigMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mmcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mmcb *MultisigMemberCreateBulk) SaveX(ctx context.Context) []*MultisigMember {
	v, err := mmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mmcb *MultisigMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := mmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmcb *MultisigMemberCreateBulk) ExecX(ctx context.Context) {
	if err := mmcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MultisigMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MultisigMemberUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (mmcb *MultisigMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *MultisigMemberUpsertBulk {
	mmcb.conflict = opts
	return &MultisigMemberUpsertBulk{
		create: mmcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MultisigMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mmcb *MultisigMemberCreateBulk) OnConflictColumns(columns ...string) *MultisigMemberUpsertBulk {
	mmcb.conflict = append(mmcb.conflict, sql.ConflictColumns(columns...))
	return &MultisigMemberUpsertBulk{
		create: mmcb,
	}
}

// MultisigMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of MultisigMember nodes.
type MultisigMemberUpsertBulk struct {
	create *MultisigMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MultisigMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(multisigmember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MultisigMemberUpsertBulk) UpdateNewValues() *MultisigMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(multisigmember.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(multisigmember.FieldCreateTime)
			}
			if _, exists := b.mutation.PublicKey(); exists {
				s.SetIgnore(multisigmember.FieldPublicKey)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MultisigMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MultisigMemberUpsertBulk) Ignore() *MultisigMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MultisigMemberUpsertBulk) DoNothing() *MultisigMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MultisigMemberCreateBulk.OnConflict
// documentation for more info.
func (u *MultisigMemberUpsertBulk) Update(set func(*MultisigMemberUpsert)) *MultisigMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MultisigMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *MultisigMemberUpsertBulk) SetUpdateTime(v time.Time) *MultisigMemberUpsertBulk {
	return u.Update(func(s *MultisigMemberUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *MultisigMemberUpsertBulk) UpdateUpdateTime() *MultisigMemberUpsertBulk {
	return u.Update(func(s *MultisigMemberUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *MultisigMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MultisigMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MultisigMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MultisigMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
