// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/multisigconfig"
)

// MultisigConfig is the model entity for the MultisigConfig schema.
type MultisigConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// SHA256 hash of the canonical MultisigConfig proto (keys sorted lexicographically)
	MultisigIdentifier []byte `json:"multisig_identifier,omitempty"`
	// Number of signatures required to authorize an action
	NumSignersThreshold uint32 `json:"num_signers_threshold,omitempty"`
	// Expected number of signers; enforced by MultisigMember creation hook
	NumSignersTotal uint32 `json:"num_signers_total,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MultisigConfigQuery when eager-loading is set.
	Edges        MultisigConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MultisigConfigEdges holds the relations/edges for other nodes in the graph.
type MultisigConfigEdges struct {
	// Members holds the value of the members edge.
	Members []*MultisigMember `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e MultisigConfigEdges) MembersOrErr() ([]*MultisigMember, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MultisigConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case multisigconfig.FieldMultisigIdentifier:
			values[i] = new([]byte)
		case multisigconfig.FieldNumSignersThreshold, multisigconfig.FieldNumSignersTotal:
			values[i] = new(sql.NullInt64)
		case multisigconfig.FieldCreateTime, multisigconfig.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case multisigconfig.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MultisigConfig fields.
func (mc *MultisigConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case multisigconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mc.ID = *value
			}
		case multisigconfig.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				mc.CreateTime = value.Time
			}
		case multisigconfig.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				mc.UpdateTime = value.Time
			}
		case multisigconfig.FieldMultisigIdentifier:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field multisig_identifier", values[i])
			} else if value != nil {
				mc.MultisigIdentifier = *value
			}
		case multisigconfig.FieldNumSignersThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field num_signers_threshold", values[i])
			} else if value.Valid {
				mc.NumSignersThreshold = uint32(value.Int64)
			}
		case multisigconfig.FieldNumSignersTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field num_signers_total", values[i])
			} else if value.Valid {
				mc.NumSignersTotal = uint32(value.Int64)
			}
		default:
			mc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MultisigConfig.
// This includes values selected through modifiers, order, etc.
func (mc *MultisigConfig) Value(name string) (ent.Value, error) {
	return mc.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the MultisigConfig entity.
func (mc *MultisigConfig) QueryMembers() *MultisigMemberQuery {
	return NewMultisigConfigClient(mc.config).QueryMembers(mc)
}

// Update returns a builder for updating this MultisigConfig.
// Note that you need to call MultisigConfig.Unwrap() before calling this method if this MultisigConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (mc *MultisigConfig) Update() *MultisigConfigUpdateOne {
	return NewMultisigConfigClient(mc.config).UpdateOne(mc)
}

// Unwrap unwraps the MultisigConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mc *MultisigConfig) Unwrap() *MultisigConfig {
	_tx, ok := mc.config.driver.(*txDriver)
	if !ok {
		panic("ent: MultisigConfig is not a transactional entity")
	}
	mc.config.driver = _tx.drv
	return mc
}

// String implements the fmt.Stringer.
func (mc *MultisigConfig) String() string {
	var builder strings.Builder
	builder.WriteString("MultisigConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mc.ID))
	builder.WriteString("create_time=")
	builder.WriteString(mc.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(mc.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("multisig_identifier=")
	builder.WriteString(fmt.Sprintf("%v", mc.MultisigIdentifier))
	builder.WriteString(", ")
	builder.WriteString("num_signers_threshold=")
	builder.WriteString(fmt.Sprintf("%v", mc.NumSignersThreshold))
	builder.WriteString(", ")
	builder.WriteString("num_signers_total=")
	builder.WriteString(fmt.Sprintf("%v", mc.NumSignersTotal))
	builder.WriteByte(')')
	return builder.String()
}

// MultisigConfigs is a parsable slice of MultisigConfig.
type MultisigConfigs []*MultisigConfig
