// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/transferreceiver"
)

// TransferReceiverUpdate is the builder for updating TransferReceiver entities.
type TransferReceiverUpdate struct {
	config
	hooks     []Hook
	mutation  *TransferReceiverMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TransferReceiverUpdate builder.
func (tru *TransferReceiverUpdate) Where(ps ...predicate.TransferReceiver) *TransferReceiverUpdate {
	tru.mutation.Where(ps...)
	return tru
}

// SetUpdateTime sets the "update_time" field.
func (tru *TransferReceiverUpdate) SetUpdateTime(t time.Time) *TransferReceiverUpdate {
	tru.mutation.SetUpdateTime(t)
	return tru
}

// SetStatus sets the "status" field.
func (tru *TransferReceiverUpdate) SetStatus(srs schematype.TransferReceiverStatus) *TransferReceiverUpdate {
	tru.mutation.SetStatus(srs)
	return tru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tru *TransferReceiverUpdate) SetNillableStatus(srs *schematype.TransferReceiverStatus) *TransferReceiverUpdate {
	if srs != nil {
		tru.SetStatus(*srs)
	}
	return tru
}

// SetCompletionTime sets the "completion_time" field.
func (tru *TransferReceiverUpdate) SetCompletionTime(t time.Time) *TransferReceiverUpdate {
	tru.mutation.SetCompletionTime(t)
	return tru
}

// SetNillableCompletionTime sets the "completion_time" field if the given value is not nil.
func (tru *TransferReceiverUpdate) SetNillableCompletionTime(t *time.Time) *TransferReceiverUpdate {
	if t != nil {
		tru.SetCompletionTime(*t)
	}
	return tru
}

// ClearCompletionTime clears the value of the "completion_time" field.
func (tru *TransferReceiverUpdate) ClearCompletionTime() *TransferReceiverUpdate {
	tru.mutation.ClearCompletionTime()
	return tru
}

// SetTransferType sets the "transfer_type" field.
func (tru *TransferReceiverUpdate) SetTransferType(st schematype.TransferType) *TransferReceiverUpdate {
	tru.mutation.SetTransferType(st)
	return tru
}

// SetNillableTransferType sets the "transfer_type" field if the given value is not nil.
func (tru *TransferReceiverUpdate) SetNillableTransferType(st *schematype.TransferType) *TransferReceiverUpdate {
	if st != nil {
		tru.SetTransferType(*st)
	}
	return tru
}

// Mutation returns the TransferReceiverMutation object of the builder.
func (tru *TransferReceiverUpdate) Mutation() *TransferReceiverMutation {
	return tru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tru *TransferReceiverUpdate) Save(ctx context.Context) (int, error) {
	if err := tru.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, tru.sqlSave, tru.mutation, tru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tru *TransferReceiverUpdate) SaveX(ctx context.Context) int {
	affected, err := tru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tru *TransferReceiverUpdate) Exec(ctx context.Context) error {
	_, err := tru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tru *TransferReceiverUpdate) ExecX(ctx context.Context) {
	if err := tru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tru *TransferReceiverUpdate) defaults() error {
	if _, ok := tru.mutation.UpdateTime(); !ok {
		if transferreceiver.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized transferreceiver.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := transferreceiver.UpdateDefaultUpdateTime()
		tru.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tru *TransferReceiverUpdate) check() error {
	if v, ok := tru.mutation.Status(); ok {
		if err := transferreceiver.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TransferReceiver.status": %w`, err)}
		}
	}
	if v, ok := tru.mutation.TransferType(); ok {
		if err := transferreceiver.TransferTypeValidator(v); err != nil {
			return &ValidationError{Name: "transfer_type", err: fmt.Errorf(`ent: validator failed for field "TransferReceiver.transfer_type": %w`, err)}
		}
	}
	if tru.mutation.TransferCleared() && len(tru.mutation.TransferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferReceiver.transfer"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tru *TransferReceiverUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransferReceiverUpdate {
	tru.modifiers = append(tru.modifiers, modifiers...)
	return tru
}

func (tru *TransferReceiverUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferreceiver.Table, transferreceiver.Columns, sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID))
	if ps := tru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tru.mutation.UpdateTime(); ok {
		_spec.SetField(transferreceiver.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tru.mutation.Status(); ok {
		_spec.SetField(transferreceiver.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tru.mutation.CompletionTime(); ok {
		_spec.SetField(transferreceiver.FieldCompletionTime, field.TypeTime, value)
	}
	if tru.mutation.CompletionTimeCleared() {
		_spec.ClearField(transferreceiver.FieldCompletionTime, field.TypeTime)
	}
	if value, ok := tru.mutation.TransferType(); ok {
		_spec.SetField(transferreceiver.FieldTransferType, field.TypeEnum, value)
	}
	_spec.AddModifiers(tru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferreceiver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tru.mutation.done = true
	return n, nil
}

// TransferReceiverUpdateOne is the builder for updating a single TransferReceiver entity.
type TransferReceiverUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TransferReceiverMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (truo *TransferReceiverUpdateOne) SetUpdateTime(t time.Time) *TransferReceiverUpdateOne {
	truo.mutation.SetUpdateTime(t)
	return truo
}

// SetStatus sets the "status" field.
func (truo *TransferReceiverUpdateOne) SetStatus(srs schematype.TransferReceiverStatus) *TransferReceiverUpdateOne {
	truo.mutation.SetStatus(srs)
	return truo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (truo *TransferReceiverUpdateOne) SetNillableStatus(srs *schematype.TransferReceiverStatus) *TransferReceiverUpdateOne {
	if srs != nil {
		truo.SetStatus(*srs)
	}
	return truo
}

// SetCompletionTime sets the "completion_time" field.
func (truo *TransferReceiverUpdateOne) SetCompletionTime(t time.Time) *TransferReceiverUpdateOne {
	truo.mutation.SetCompletionTime(t)
	return truo
}

// SetNillableCompletionTime sets the "completion_time" field if the given value is not nil.
func (truo *TransferReceiverUpdateOne) SetNillableCompletionTime(t *time.Time) *TransferReceiverUpdateOne {
	if t != nil {
		truo.SetCompletionTime(*t)
	}
	return truo
}

// ClearCompletionTime clears the value of the "completion_time" field.
func (truo *TransferReceiverUpdateOne) ClearCompletionTime() *TransferReceiverUpdateOne {
	truo.mutation.ClearCompletionTime()
	return truo
}

// SetTransferType sets the "transfer_type" field.
func (truo *TransferReceiverUpdateOne) SetTransferType(st schematype.TransferType) *TransferReceiverUpdateOne {
	truo.mutation.SetTransferType(st)
	return truo
}

// SetNillableTransferType sets the "transfer_type" field if the given value is not nil.
func (truo *TransferReceiverUpdateOne) SetNillableTransferType(st *schematype.TransferType) *TransferReceiverUpdateOne {
	if st != nil {
		truo.SetTransferType(*st)
	}
	return truo
}

// Mutation returns the TransferReceiverMutation object of the builder.
func (truo *TransferReceiverUpdateOne) Mutation() *TransferReceiverMutation {
	return truo.mutation
}

// Where appends a list predicates to the TransferReceiverUpdate builder.
func (truo *TransferReceiverUpdateOne) Where(ps ...predicate.TransferReceiver) *TransferReceiverUpdateOne {
	truo.mutation.Where(ps...)
	return truo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (truo *TransferReceiverUpdateOne) Select(field string, fields ...string) *TransferReceiverUpdateOne {
	truo.fields = append([]string{field}, fields...)
	return truo
}

// Save executes the query and returns the updated TransferReceiver entity.
func (truo *TransferReceiverUpdateOne) Save(ctx context.Context) (*TransferReceiver, error) {
	if err := truo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, truo.sqlSave, truo.mutation, truo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (truo *TransferReceiverUpdateOne) SaveX(ctx context.Context) *TransferReceiver {
	node, err := truo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (truo *TransferReceiverUpdateOne) Exec(ctx context.Context) error {
	_, err := truo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (truo *TransferReceiverUpdateOne) ExecX(ctx context.Context) {
	if err := truo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (truo *TransferReceiverUpdateOne) defaults() error {
	if _, ok := truo.mutation.UpdateTime(); !ok {
		if transferreceiver.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized transferreceiver.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := transferreceiver.UpdateDefaultUpdateTime()
		truo.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (truo *TransferReceiverUpdateOne) check() error {
	if v, ok := truo.mutation.Status(); ok {
		if err := transferreceiver.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TransferReceiver.status": %w`, err)}
		}
	}
	if v, ok := truo.mutation.TransferType(); ok {
		if err := transferreceiver.TransferTypeValidator(v); err != nil {
			return &ValidationError{Name: "transfer_type", err: fmt.Errorf(`ent: validator failed for field "TransferReceiver.transfer_type": %w`, err)}
		}
	}
	if truo.mutation.TransferCleared() && len(truo.mutation.TransferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferReceiver.transfer"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (truo *TransferReceiverUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransferReceiverUpdateOne {
	truo.modifiers = append(truo.modifiers, modifiers...)
	return truo
}

func (truo *TransferReceiverUpdateOne) sqlSave(ctx context.Context) (_node *TransferReceiver, err error) {
	if err := truo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferreceiver.Table, transferreceiver.Columns, sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID))
	id, ok := truo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransferReceiver.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := truo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transferreceiver.FieldID)
		for _, f := range fields {
			if !transferreceiver.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transferreceiver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := truo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := truo.mutation.UpdateTime(); ok {
		_spec.SetField(transferreceiver.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := truo.mutation.Status(); ok {
		_spec.SetField(transferreceiver.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := truo.mutation.CompletionTime(); ok {
		_spec.SetField(transferreceiver.FieldCompletionTime, field.TypeTime, value)
	}
	if truo.mutation.CompletionTimeCleared() {
		_spec.ClearField(transferreceiver.FieldCompletionTime, field.TypeTime)
	}
	if value, ok := truo.mutation.TransferType(); ok {
		_spec.SetField(transferreceiver.FieldTransferType, field.TypeEnum, value)
	}
	_spec.AddModifiers(truo.modifiers...)
	_node = &TransferReceiver{config: truo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, truo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferreceiver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	truo.mutation.done = true
	return _node, nil
}
