// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/partner"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/transfer"
	"github.com/lightsparkdev/spark/so/ent/transferpartner"
)

// TransferPartner is the model entity for the TransferPartner schema.
type TransferPartner struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The type of operation: LIGHTNING_SEND, LIGHTNING_RECEIVE, or TRANSFER.
	Type schematype.TransferPartnerType `json:"type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransferPartnerQuery when eager-loading is set.
	Edges                     TransferPartnerEdges `json:"edges"`
	transfer_partner_partner  *uuid.UUID
	transfer_partner_transfer *uuid.UUID
	selectValues              sql.SelectValues
}

// TransferPartnerEdges holds the relations/edges for other nodes in the graph.
type TransferPartnerEdges struct {
	// The partner that initiated this transfer.
	Partner *Partner `json:"partner,omitempty"`
	// The transfer associated with this partner attribution.
	Transfer *Transfer `json:"transfer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PartnerOrErr returns the Partner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransferPartnerEdges) PartnerOrErr() (*Partner, error) {
	if e.Partner != nil {
		return e.Partner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: partner.Label}
	}
	return nil, &NotLoadedError{edge: "partner"}
}

// TransferOrErr returns the Transfer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransferPartnerEdges) TransferOrErr() (*Transfer, error) {
	if e.Transfer != nil {
		return e.Transfer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: transfer.Label}
	}
	return nil, &NotLoadedError{edge: "transfer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TransferPartner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transferpartner.FieldType:
			values[i] = new(sql.NullString)
		case transferpartner.FieldCreateTime, transferpartner.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case transferpartner.FieldID:
			values[i] = new(uuid.UUID)
		case transferpartner.ForeignKeys[0]: // transfer_partner_partner
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case transferpartner.ForeignKeys[1]: // transfer_partner_transfer
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TransferPartner fields.
func (tp *TransferPartner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transferpartner.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tp.ID = *value
			}
		case transferpartner.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				tp.CreateTime = value.Time
			}
		case transferpartner.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				tp.UpdateTime = value.Time
			}
		case transferpartner.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				tp.Type = schematype.TransferPartnerType(value.String)
			}
		case transferpartner.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field transfer_partner_partner", values[i])
			} else if value.Valid {
				tp.transfer_partner_partner = new(uuid.UUID)
				*tp.transfer_partner_partner = *value.S.(*uuid.UUID)
			}
		case transferpartner.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field transfer_partner_transfer", values[i])
			} else if value.Valid {
				tp.transfer_partner_transfer = new(uuid.UUID)
				*tp.transfer_partner_transfer = *value.S.(*uuid.UUID)
			}
		default:
			tp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TransferPartner.
// This includes values selected through modifiers, order, etc.
func (tp *TransferPartner) Value(name string) (ent.Value, error) {
	return tp.selectValues.Get(name)
}

// QueryPartner queries the "partner" edge of the TransferPartner entity.
func (tp *TransferPartner) QueryPartner() *PartnerQuery {
	return NewTransferPartnerClient(tp.config).QueryPartner(tp)
}

// QueryTransfer queries the "transfer" edge of the TransferPartner entity.
func (tp *TransferPartner) QueryTransfer() *TransferQuery {
	return NewTransferPartnerClient(tp.config).QueryTransfer(tp)
}

// Update returns a builder for updating this TransferPartner.
// Note that you need to call TransferPartner.Unwrap() before calling this method if this TransferPartner
// was returned from a transaction, and the transaction was committed or rolled back.
func (tp *TransferPartner) Update() *TransferPartnerUpdateOne {
	return NewTransferPartnerClient(tp.config).UpdateOne(tp)
}

// Unwrap unwraps the TransferPartner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tp *TransferPartner) Unwrap() *TransferPartner {
	_tx, ok := tp.config.driver.(*txDriver)
	if !ok {
		panic("ent: TransferPartner is not a transactional entity")
	}
	tp.config.driver = _tx.drv
	return tp
}

// String implements the fmt.Stringer.
func (tp *TransferPartner) String() string {
	var builder strings.Builder
	builder.WriteString("TransferPartner(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tp.ID))
	builder.WriteString("create_time=")
	builder.WriteString(tp.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(tp.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", tp.Type))
	builder.WriteByte(')')
	return builder.String()
}

// TransferPartners is a parsable slice of TransferPartner.
type TransferPartners []*TransferPartner
