// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/transfer"
	"github.com/lightsparkdev/spark/so/ent/transferreceiver"
)

// TransferReceiverCreate is the builder for creating a TransferReceiver entity.
type TransferReceiverCreate struct {
	config
	mutation *TransferReceiverMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (trc *TransferReceiverCreate) SetCreateTime(t time.Time) *TransferReceiverCreate {
	trc.mutation.SetCreateTime(t)
	return trc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (trc *TransferReceiverCreate) SetNillableCreateTime(t *time.Time) *TransferReceiverCreate {
	if t != nil {
		trc.SetCreateTime(*t)
	}
	return trc
}

// SetUpdateTime sets the "update_time" field.
func (trc *TransferReceiverCreate) SetUpdateTime(t time.Time) *TransferReceiverCreate {
	trc.mutation.SetUpdateTime(t)
	return trc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (trc *TransferReceiverCreate) SetNillableUpdateTime(t *time.Time) *TransferReceiverCreate {
	if t != nil {
		trc.SetUpdateTime(*t)
	}
	return trc
}

// SetTransferID sets the "transfer_id" field.
func (trc *TransferReceiverCreate) SetTransferID(u uuid.UUID) *TransferReceiverCreate {
	trc.mutation.SetTransferID(u)
	return trc
}

// SetIdentityPubkey sets the "identity_pubkey" field.
func (trc *TransferReceiverCreate) SetIdentityPubkey(k keys.Public) *TransferReceiverCreate {
	trc.mutation.SetIdentityPubkey(k)
	return trc
}

// SetStatus sets the "status" field.
func (trc *TransferReceiverCreate) SetStatus(srs schematype.TransferReceiverStatus) *TransferReceiverCreate {
	trc.mutation.SetStatus(srs)
	return trc
}

// SetCompletionTime sets the "completion_time" field.
func (trc *TransferReceiverCreate) SetCompletionTime(t time.Time) *TransferReceiverCreate {
	trc.mutation.SetCompletionTime(t)
	return trc
}

// SetNillableCompletionTime sets the "completion_time" field if the given value is not nil.
func (trc *TransferReceiverCreate) SetNillableCompletionTime(t *time.Time) *TransferReceiverCreate {
	if t != nil {
		trc.SetCompletionTime(*t)
	}
	return trc
}

// SetTransferType sets the "transfer_type" field.
func (trc *TransferReceiverCreate) SetTransferType(st schematype.TransferType) *TransferReceiverCreate {
	trc.mutation.SetTransferType(st)
	return trc
}

// SetID sets the "id" field.
func (trc *TransferReceiverCreate) SetID(u uuid.UUID) *TransferReceiverCreate {
	trc.mutation.SetID(u)
	return trc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (trc *TransferReceiverCreate) SetNillableID(u *uuid.UUID) *TransferReceiverCreate {
	if u != nil {
		trc.SetID(*u)
	}
	return trc
}

// SetTransfer sets the "transfer" edge to the Transfer entity.
func (trc *TransferReceiverCreate) SetTransfer(t *Transfer) *TransferReceiverCreate {
	return trc.SetTransferID(t.ID)
}

// Mutation returns the TransferReceiverMutation object of the builder.
func (trc *TransferReceiverCreate) Mutation() *TransferReceiverMutation {
	return trc.mutation
}

// Save creates the TransferReceiver in the database.
func (trc *TransferReceiverCreate) Save(ctx context.Context) (*TransferReceiver, error) {
	if err := trc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, trc.sqlSave, trc.mutation, trc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (trc *TransferReceiverCreate) SaveX(ctx context.Context) *TransferReceiver {
	v, err := trc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trc *TransferReceiverCreate) Exec(ctx context.Context) error {
	_, err := trc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trc *TransferReceiverCreate) ExecX(ctx context.Context) {
	if err := trc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (trc *TransferReceiverCreate) defaults() error {
	if _, ok := trc.mutation.CreateTime(); !ok {
		if transferreceiver.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized transferreceiver.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := transferreceiver.DefaultCreateTime()
		trc.mutation.SetCreateTime(v)
	}
	if _, ok := trc.mutation.UpdateTime(); !ok {
		if transferreceiver.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized transferreceiver.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := transferreceiver.DefaultUpdateTime()
		trc.mutation.SetUpdateTime(v)
	}
	if _, ok := trc.mutation.ID(); !ok {
		if transferreceiver.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized transferreceiver.DefaultID (forgotten import ent/runtime?)")
		}
		v := transferreceiver.DefaultID()
		trc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (trc *TransferReceiverCreate) check() error {
	if _, ok := trc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "TransferReceiver.create_time"`)}
	}
	if _, ok := trc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "TransferReceiver.update_time"`)}
	}
	if _, ok := trc.mutation.TransferID(); !ok {
		return &ValidationError{Name: "transfer_id", err: errors.New(`ent: missing required field "TransferReceiver.transfer_id"`)}
	}
	if _, ok := trc.mutation.IdentityPubkey(); !ok {
		return &ValidationError{Name: "identity_pubkey", err: errors.New(`ent: missing required field "TransferReceiver.identity_pubkey"`)}
	}
	if _, ok := trc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TransferReceiver.status"`)}
	}
	if v, ok := trc.mutation.Status(); ok {
		if err := transferreceiver.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TransferReceiver.status": %w`, err)}
		}
	}
	if _, ok := trc.mutation.TransferType(); !ok {
		return &ValidationError{Name: "transfer_type", err: errors.New(`ent: missing required field "TransferReceiver.transfer_type"`)}
	}
	if v, ok := trc.mutation.TransferType(); ok {
		if err := transferreceiver.TransferTypeValidator(v); err != nil {
			return &ValidationError{Name: "transfer_type", err: fmt.Errorf(`ent: validator failed for field "TransferReceiver.transfer_type": %w`, err)}
		}
	}
	if len(trc.mutation.TransferIDs()) == 0 {
		return &ValidationError{Name: "transfer", err: errors.New(`ent: missing required edge "TransferReceiver.transfer"`)}
	}
	return nil
}

func (trc *TransferReceiverCreate) sqlSave(ctx context.Context) (*TransferReceiver, error) {
	if err := trc.check(); err != nil {
		return nil, err
	}
	_node, _spec := trc.createSpec()
	if err := sqlgraph.CreateNode(ctx, trc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	trc.mutation.id = &_node.ID
	trc.mutation.done = true
	return _node, nil
}

func (trc *TransferReceiverCreate) createSpec() (*TransferReceiver, *sqlgraph.CreateSpec) {
	var (
		_node = &TransferReceiver{config: trc.config}
		_spec = sqlgraph.NewCreateSpec(transferreceiver.Table, sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = trc.conflict
	if id, ok := trc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := trc.mutation.CreateTime(); ok {
		_spec.SetField(transferreceiver.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := trc.mutation.UpdateTime(); ok {
		_spec.SetField(transferreceiver.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := trc.mutation.IdentityPubkey(); ok {
		_spec.SetField(transferreceiver.FieldIdentityPubkey, field.TypeBytes, value)
		_node.IdentityPubkey = value
	}
	if value, ok := trc.mutation.Status(); ok {
		_spec.SetField(transferreceiver.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := trc.mutation.CompletionTime(); ok {
		_spec.SetField(transferreceiver.FieldCompletionTime, field.TypeTime, value)
		_node.CompletionTime = value
	}
	if value, ok := trc.mutation.TransferType(); ok {
		_spec.SetField(transferreceiver.FieldTransferType, field.TypeEnum, value)
		_node.TransferType = value
	}
	if nodes := trc.mutation.TransferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferreceiver.TransferTable,
			Columns: []string{transferreceiver.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TransferID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TransferReceiver.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransferReceiverUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (trc *TransferReceiverCreate) OnConflict(opts ...sql.ConflictOption) *TransferReceiverUpsertOne {
	trc.conflict = opts
	return &TransferReceiverUpsertOne{
		create: trc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TransferReceiver.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (trc *TransferReceiverCreate) OnConflictColumns(columns ...string) *TransferReceiverUpsertOne {
	trc.conflict = append(trc.conflict, sql.ConflictColumns(columns...))
	return &TransferReceiverUpsertOne{
		create: trc,
	}
}

type (
	// TransferReceiverUpsertOne is the builder for "upsert"-ing
	//  one TransferReceiver node.
	TransferReceiverUpsertOne struct {
		create *TransferReceiverCreate
	}

	// TransferReceiverUpsert is the "OnConflict" setter.
	TransferReceiverUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TransferReceiverUpsert) SetUpdateTime(v time.Time) *TransferReceiverUpsert {
	u.Set(transferreceiver.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TransferReceiverUpsert) UpdateUpdateTime() *TransferReceiverUpsert {
	u.SetExcluded(transferreceiver.FieldUpdateTime)
	return u
}

// SetStatus sets the "status" field.
func (u *TransferReceiverUpsert) SetStatus(v schematype.TransferReceiverStatus) *TransferReceiverUpsert {
	u.Set(transferreceiver.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TransferReceiverUpsert) UpdateStatus() *TransferReceiverUpsert {
	u.SetExcluded(transferreceiver.FieldStatus)
	return u
}

// SetCompletionTime sets the "completion_time" field.
func (u *TransferReceiverUpsert) SetCompletionTime(v time.Time) *TransferReceiverUpsert {
	u.Set(transferreceiver.FieldCompletionTime, v)
	return u
}

// UpdateCompletionTime sets the "completion_time" field to the value that was provided on create.
func (u *TransferReceiverUpsert) UpdateCompletionTime() *TransferReceiverUpsert {
	u.SetExcluded(transferreceiver.FieldCompletionTime)
	return u
}

// ClearCompletionTime clears the value of the "completion_time" field.
func (u *TransferReceiverUpsert) ClearCompletionTime() *TransferReceiverUpsert {
	u.SetNull(transferreceiver.FieldCompletionTime)
	return u
}

// SetTransferType sets the "transfer_type" field.
func (u *TransferReceiverUpsert) SetTransferType(v schematype.TransferType) *TransferReceiverUpsert {
	u.Set(transferreceiver.FieldTransferType, v)
	return u
}

// UpdateTransferType sets the "transfer_type" field to the value that was provided on create.
func (u *TransferReceiverUpsert) UpdateTransferType() *TransferReceiverUpsert {
	u.SetExcluded(transferreceiver.FieldTransferType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TransferReceiver.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(transferreceiver.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TransferReceiverUpsertOne) UpdateNewValues() *TransferReceiverUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(transferreceiver.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(transferreceiver.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TransferID(); exists {
			s.SetIgnore(transferreceiver.FieldTransferID)
		}
		if _, exists := u.create.mutation.IdentityPubkey(); exists {
			s.SetIgnore(transferreceiver.FieldIdentityPubkey)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TransferReceiver.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TransferReceiverUpsertOne) Ignore() *TransferReceiverUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransferReceiverUpsertOne) DoNothing() *TransferReceiverUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransferReceiverCreate.OnConflict
// documentation for more info.
func (u *TransferReceiverUpsertOne) Update(set func(*TransferReceiverUpsert)) *TransferReceiverUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransferReceiverUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TransferReceiverUpsertOne) SetUpdateTime(v time.Time) *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TransferReceiverUpsertOne) UpdateUpdateTime() *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *TransferReceiverUpsertOne) SetStatus(v schematype.TransferReceiverStatus) *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TransferReceiverUpsertOne) UpdateStatus() *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateStatus()
	})
}

// SetCompletionTime sets the "completion_time" field.
func (u *TransferReceiverUpsertOne) SetCompletionTime(v time.Time) *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetCompletionTime(v)
	})
}

// UpdateCompletionTime sets the "completion_time" field to the value that was provided on create.
func (u *TransferReceiverUpsertOne) UpdateCompletionTime() *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateCompletionTime()
	})
}

// ClearCompletionTime clears the value of the "completion_time" field.
func (u *TransferReceiverUpsertOne) ClearCompletionTime() *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.ClearCompletionTime()
	})
}

// SetTransferType sets the "transfer_type" field.
func (u *TransferReceiverUpsertOne) SetTransferType(v schematype.TransferType) *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetTransferType(v)
	})
}

// UpdateTransferType sets the "transfer_type" field to the value that was provided on create.
func (u *TransferReceiverUpsertOne) UpdateTransferType() *TransferReceiverUpsertOne {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateTransferType()
	})
}

// Exec executes the query.
func (u *TransferReceiverUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransferReceiverCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransferReceiverUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TransferReceiverUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TransferReceiverUpsertOne.ID is not supported by MySQL driver. Use TransferReceiverUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TransferReceiverUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TransferReceiverCreateBulk is the builder for creating many TransferReceiver entities in bulk.
type TransferReceiverCreateBulk struct {
	config
	err      error
	builders []*TransferReceiverCreate
	conflict []sql.ConflictOption
}

// Save creates the TransferReceiver entities in the database.
func (trcb *TransferReceiverCreateBulk) Save(ctx context.Context) ([]*TransferReceiver, error) {
	if trcb.err != nil {
		return nil, trcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(trcb.builders))
	nodes := make([]*TransferReceiver, len(trcb.builders))
	mutators := make([]Mutator, len(trcb.builders))
	for i := range trcb.builders {
		func(i int, root context.Context) {
			builder := trcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransferReceiverMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, trcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = trcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, trcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, trcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (trcb *TransferReceiverCreateBulk) SaveX(ctx context.Context) []*TransferReceiver {
	v, err := trcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trcb *TransferReceiverCreateBulk) Exec(ctx context.Context) error {
	_, err := trcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trcb *TransferReceiverCreateBulk) ExecX(ctx context.Context) {
	if err := trcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TransferReceiver.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransferReceiverUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (trcb *TransferReceiverCreateBulk) OnConflict(opts ...sql.ConflictOption) *TransferReceiverUpsertBulk {
	trcb.conflict = opts
	return &TransferReceiverUpsertBulk{
		create: trcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TransferReceiver.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (trcb *TransferReceiverCreateBulk) OnConflictColumns(columns ...string) *TransferReceiverUpsertBulk {
	trcb.conflict = append(trcb.conflict, sql.ConflictColumns(columns...))
	return &TransferReceiverUpsertBulk{
		create: trcb,
	}
}

// TransferReceiverUpsertBulk is the builder for "upsert"-ing
// a bulk of TransferReceiver nodes.
type TransferReceiverUpsertBulk struct {
	create *TransferReceiverCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TransferReceiver.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(transferreceiver.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TransferReceiverUpsertBulk) UpdateNewValues() *TransferReceiverUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(transferreceiver.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(transferreceiver.FieldCreateTime)
			}
			if _, exists := b.mutation.TransferID(); exists {
				s.SetIgnore(transferreceiver.FieldTransferID)
			}
			if _, exists := b.mutation.IdentityPubkey(); exists {
				s.SetIgnore(transferreceiver.FieldIdentityPubkey)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TransferReceiver.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TransferReceiverUpsertBulk) Ignore() *TransferReceiverUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransferReceiverUpsertBulk) DoNothing() *TransferReceiverUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransferReceiverCreateBulk.OnConflict
// documentation for more info.
func (u *TransferReceiverUpsertBulk) Update(set func(*TransferReceiverUpsert)) *TransferReceiverUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransferReceiverUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TransferReceiverUpsertBulk) SetUpdateTime(v time.Time) *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TransferReceiverUpsertBulk) UpdateUpdateTime() *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *TransferReceiverUpsertBulk) SetStatus(v schematype.TransferReceiverStatus) *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TransferReceiverUpsertBulk) UpdateStatus() *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateStatus()
	})
}

// SetCompletionTime sets the "completion_time" field.
func (u *TransferReceiverUpsertBulk) SetCompletionTime(v time.Time) *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetCompletionTime(v)
	})
}

// UpdateCompletionTime sets the "completion_time" field to the value that was provided on create.
func (u *TransferReceiverUpsertBulk) UpdateCompletionTime() *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateCompletionTime()
	})
}

// ClearCompletionTime clears the value of the "completion_time" field.
func (u *TransferReceiverUpsertBulk) ClearCompletionTime() *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.ClearCompletionTime()
	})
}

// SetTransferType sets the "transfer_type" field.
func (u *TransferReceiverUpsertBulk) SetTransferType(v schematype.TransferType) *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.SetTransferType(v)
	})
}

// UpdateTransferType sets the "transfer_type" field to the value that was provided on create.
func (u *TransferReceiverUpsertBulk) UpdateTransferType() *TransferReceiverUpsertBulk {
	return u.Update(func(s *TransferReceiverUpsert) {
		s.UpdateTransferType()
	})
}

// Exec executes the query.
func (u *TransferReceiverUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TransferReceiverCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransferReceiverCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransferReceiverUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
