// Code generated by ent, DO NOT EDIT.

package transfersender

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldUpdateTime, v))
}

// TransferID applies equality check predicate on the "transfer_id" field. It's identical to TransferIDEQ.
func TransferID(v uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldTransferID, v))
}

// IdentityPubkey applies equality check predicate on the "identity_pubkey" field. It's identical to IdentityPubkeyEQ.
func IdentityPubkey(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldIdentityPubkey, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLTE(FieldUpdateTime, v))
}

// TransferIDEQ applies the EQ predicate on the "transfer_id" field.
func TransferIDEQ(v uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldTransferID, v))
}

// TransferIDNEQ applies the NEQ predicate on the "transfer_id" field.
func TransferIDNEQ(v uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNEQ(FieldTransferID, v))
}

// TransferIDIn applies the In predicate on the "transfer_id" field.
func TransferIDIn(vs ...uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldIn(FieldTransferID, vs...))
}

// TransferIDNotIn applies the NotIn predicate on the "transfer_id" field.
func TransferIDNotIn(vs ...uuid.UUID) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNotIn(FieldTransferID, vs...))
}

// IdentityPubkeyEQ applies the EQ predicate on the "identity_pubkey" field.
func IdentityPubkeyEQ(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldEQ(FieldIdentityPubkey, v))
}

// IdentityPubkeyNEQ applies the NEQ predicate on the "identity_pubkey" field.
func IdentityPubkeyNEQ(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNEQ(FieldIdentityPubkey, v))
}

// IdentityPubkeyIn applies the In predicate on the "identity_pubkey" field.
func IdentityPubkeyIn(vs ...keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldIn(FieldIdentityPubkey, vs...))
}

// IdentityPubkeyNotIn applies the NotIn predicate on the "identity_pubkey" field.
func IdentityPubkeyNotIn(vs ...keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldNotIn(FieldIdentityPubkey, vs...))
}

// IdentityPubkeyGT applies the GT predicate on the "identity_pubkey" field.
func IdentityPubkeyGT(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGT(FieldIdentityPubkey, v))
}

// IdentityPubkeyGTE applies the GTE predicate on the "identity_pubkey" field.
func IdentityPubkeyGTE(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldGTE(FieldIdentityPubkey, v))
}

// IdentityPubkeyLT applies the LT predicate on the "identity_pubkey" field.
func IdentityPubkeyLT(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLT(FieldIdentityPubkey, v))
}

// IdentityPubkeyLTE applies the LTE predicate on the "identity_pubkey" field.
func IdentityPubkeyLTE(v keys.Public) predicate.TransferSender {
	return predicate.TransferSender(sql.FieldLTE(FieldIdentityPubkey, v))
}

// TransferTypeEQ applies the EQ predicate on the "transfer_type" field.
func TransferTypeEQ(v schematype.TransferType) predicate.TransferSender {
	vc := v
	return predicate.TransferSender(sql.FieldEQ(FieldTransferType, vc))
}

// TransferTypeNEQ applies the NEQ predicate on the "transfer_type" field.
func TransferTypeNEQ(v schematype.TransferType) predicate.TransferSender {
	vc := v
	return predicate.TransferSender(sql.FieldNEQ(FieldTransferType, vc))
}

// TransferTypeIn applies the In predicate on the "transfer_type" field.
func TransferTypeIn(vs ...schematype.TransferType) predicate.TransferSender {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TransferSender(sql.FieldIn(FieldTransferType, v...))
}

// TransferTypeNotIn applies the NotIn predicate on the "transfer_type" field.
func TransferTypeNotIn(vs ...schematype.TransferType) predicate.TransferSender {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TransferSender(sql.FieldNotIn(FieldTransferType, v...))
}

// HasTransfer applies the HasEdge predicate on the "transfer" edge.
func HasTransfer() predicate.TransferSender {
	return predicate.TransferSender(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TransferTable, TransferColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransferWith applies the HasEdge predicate on the "transfer" edge with a given conditions (other predicates).
func HasTransferWith(preds ...predicate.Transfer) predicate.TransferSender {
	return predicate.TransferSender(func(s *sql.Selector) {
		step := newTransferStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransferSender) predicate.TransferSender {
	return predicate.TransferSender(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransferSender) predicate.TransferSender {
	return predicate.TransferSender(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransferSender) predicate.TransferSender {
	return predicate.TransferSender(sql.NotPredicates(p))
}
