import base from "@lightsparkdev/eslint-config/base";

export default [
  {
    // Stage the first lint rollout without downgrading the shared base rules.
    // These dynamic boundaries need dedicated type cleanup before opt-in.
    ignores: [
      "src/graphql/objects/**",
      "src/graphql/client.ts",
      "src/auto-bind.ts",
      "src/bare/index.ts",
      "src/constants.ts",
      "src/proto/**",
      "src/services/bolt11-spark.ts",
      "src/services/config.ts",
      "src/services/connection/connection.browser.ts",
      "src/services/connection/connection.node.ts",
      "src/services/connection/connection.ts",
      "src/services/leaf-manager.ts",
      "src/services/swap.ts",
      "src/services/tokens/token-transactions.ts",
      "src/services/transfer.ts",
      "src/services/xhr-transport.ts",
      "src/signer/signer.ts",
      "src/spark-bindings/spark-bindings.browser.ts",
      "src/spark-bindings/spark-bindings.node.ts",
      "src/spark-bindings/spark-bindings.ts",
      "src/spark-bindings/wasm/**",
      "src/spark-wallet/proto-hash.ts",
      "src/spark-wallet/spark-wallet.ts",
      "src/tests/**",
      "src/token-primitives-bindings/token-primitives-bindings.browser.ts",
      "src/token-primitives-bindings/token-primitives-bindings.node.ts",
      "src/token-primitives-bindings/wasm/**",
      "src/utils/address.ts",
      "src/utils/bitcoin.ts",
      "src/utils/fetch.ts",
      "src/utils/htlc-transactions.ts",
      "src/utils/invoice-hashing.ts",
      "src/utils/logging-service.ts",
      "src/utils/mempool.ts",
      "src/utils/method-logger.ts",
      "src/utils/network.ts",
      "src/utils/response-validation.ts",
      "src/utils/retry.ts",
      "src/utils/token-hashing.ts",
      "src/utils/token-transaction-validation.ts",
      "src/utils/token-transactions.ts",
      "src/utils/unilateral-exit.ts",
      "src/utils/xchain-address.ts",
      "src/wasm/**",
      "**/*.test.ts",
      "scripts/generate-hashes.mjs",
      "wasm/**",
    ],
  },
  ...base,
];
