package schema

import (
	"context"
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common"
	bitcointransaction "github.com/lightsparkdev/spark/common/bitcoin_transaction"
	gen "github.com/lightsparkdev/spark/so/ent"
	"github.com/lightsparkdev/spark/so/ent/hook"
	st "github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/entexample"
)

// TransferLeaf is the junction schema between Transfer and TreeNode.
type TransferLeaf struct {
	ent.Schema
}

// Mixin is the mixin for the TransferLeaf table.
func (TransferLeaf) Mixin() []ent.Mixin {
	return []ent.Mixin{
		BaseMixin{},
	}
}

// Fields are the fields for the TransferLeaf table.
func (TransferLeaf) Fields() []ent.Field {
	return []ent.Field{
		field.Bytes("secret_cipher").
			Optional().
			Comment("Encrypted secret cipher from the sender to the receiver, containing the key tweak.").
			Annotations(entexample.Default(
				"042d6a7113c2a422c6b7fe019d2f7f06efd9d8acd8ddadcb79081b3d1ef6a8663fd9d139a0d60a38813afc50df1c28776bb41785e2023740ae9a9dce40b5dfd5d3d5c547e276b5e78f21f8ccb273e6a94861e97506f393951a08ab5df3f18ee25662931e0aef1b18957d163a7cd1271fb56dcfd0bc62ecc0051d4be08912ff6b5b",
			)),
		field.Bytes("signature").
			Optional().
			Comment("Signature from the sender over the transfer leaf data.").
			Annotations(entexample.Default(
				"ed9ffdb0a3a65a5e51e477cb6688c118e5bb4333a8bd8c8dbe4b5e7d4223f97b6c4947d300d34d4cf48d2d1bd03c8aec29f628175a5c7d37a6e7338270af8f4d",
			)),
		field.Bytes("previous_refund_tx").
			NotEmpty().
			Immutable().
			Comment("The previous owner's refund transaction (pre-signed), replaced by this transfer.").
			Annotations(entexample.Default(
				"03000000000101518e95707c9e80d03728e1a98e64e554a1d0d8870fedd8562114f682f874a96c0000000000c800004002080000000000000022512081c69ace46df7d545ad8248d6b73dfb15035237f52c97e7ed02edb527950c3e900000000000000000451024e730140232049133699c055b5c005caea4e146645c347ca7837be573e3140e46c46edbfb457dd90348027306234a7caa0a358a6007d54aab2b8bf4964a1b2eacab9845800000000",
			)),
		field.Bytes("previous_direct_refund_tx").
			Optional().
			Immutable().
			Comment("The previous owner's direct refund transaction (pre-signed), if applicable.").
			Annotations(entexample.Default(
				"0300000000010118e1168422131841f6bd3d9c403478a1a0b8776aa6166ba47ca4eb0a253f71270000000000fa00004001080000000000000022512081c69ace46df7d545ad8248d6b73dfb15035237f52c97e7ed02edb527950c3e9014073d4f0dbfc25085d7074f340eaf71ccf5e70e6b30b2754d3c9c6804fc28a55d2efaea754e5b5532cd581d73cbcfa22f3ccf0fac1cc642890668b4569ee68f69b00000000",
			)),
		field.Bytes("previous_direct_from_cpfp_refund_tx").
			Optional().
			Immutable().
			Comment("The previous owner's direct-from-CPFP refund transaction (pre-signed), if applicable."),
		field.Bytes("intermediate_refund_tx").
			NotEmpty().
			Comment("The new intermediate refund transaction for the receiver.").
			Annotations(entexample.Default(
				"03000000000101518e95707c9e80d03728e1a98e64e554a1d0d8870fedd8562114f682f874a96c0000000000aa0000400208000000000000002251207f7760827164bad5a01c73f73efb1b060d412c24d0154f404574ecee5ef03aa800000000000000000451024e7301401f10f350a49366f9e5e1ab05ffc39c90a3e410bc74688cfec8eefcf001ce29cdb260d5461614f6f56e4d1fdf5026b177ed9ea0bb3a89d5519e47ae50b3c016e500000000",
			)),
		field.Bytes("intermediate_direct_refund_tx").
			Optional().
			Comment("The new intermediate direct refund transaction for the receiver, if applicable.").
			Annotations(entexample.Default(
				"0300000000010118e1168422131841f6bd3d9c403478a1a0b8776aa6166ba47ca4eb0a253f71270000000000b90000400108000000000000002251207f7760827164bad5a01c73f73efb1b060d412c24d0154f404574ecee5ef03aa801403fd09e818a55ebc3d768f17aac9d278875053115c7927b87bda75c8740b2a1245a13f9a1642715a25ee699ee67ef9af3392376537dd5e9f60207c9a3d1411ca800000000",
			)),
		field.Bytes("intermediate_direct_from_cpfp_refund_tx").
			Optional().
			Comment("The new intermediate direct-from-CPFP refund transaction for the receiver, if applicable.").
			Annotations(entexample.Default(
				"03000000000101518e95707c9e80d03728e1a98e64e554a1d0d8870fedd8562114f682f874a96c0000000000b90000400108000000000000002251207f7760827164bad5a01c73f73efb1b060d412c24d0154f404574ecee5ef03aa801409684ee10c0407a47b467df3f5cee375a694f44fad47d5c9d0225335e69bdcdb8131ec93299239bb35b06cbe8601d0f10fd3438d1b9c96716b1ab156c00e840c300000000",
			)),
		field.Bytes("intermediate_refund_txid").
			Optional().
			GoType(st.TxID{}).
			Comment("Valid transaction ID of the stored intermediate refund transaction. Generated by hooks from intermediate_refund_tx.").
			Annotations(entexample.Default(
				"ce9d4868d3c7a3529bc1f3d5c1af72768311a269ea530236653d2620431cac57",
			)),
		field.Bytes("intermediate_direct_refund_txid").
			Optional().
			GoType(st.TxID{}).
			Comment("Valid transaction ID of the stored intermediate direct refund transaction. Generated by hooks from intermediate_direct_refund_tx.").
			Annotations(entexample.Default(
				"0747a639d09c548001954cbda5969a19ab69f30c2bca7244327e1f3a8fdf1817",
			)),
		field.Bytes("intermediate_direct_from_cpfp_refund_txid").
			Optional().
			GoType(st.TxID{}).
			Comment("Valid transaction ID of the stored intermediate direct from CPFP refund transaction. Generated by hooks from intermediate_direct_from_cpfp_refund_tx.").
			Annotations(entexample.Default(
				"eac6c654e9b82aeea95fbdfc4c0f9b1ee41300503949fd5535f037fbcd49ed55",
			)),
		field.Uint64("intermediate_refund_timelock").
			Optional().
			Comment("Timelock value extracted from intermediate_refund_tx. Generated by hooks.").
			Annotations(entexample.Default(170)),
		field.Uint64("intermediate_direct_refund_timelock").
			Optional().
			Comment("Timelock value extracted from intermediate_direct_refund_tx. Generated by hooks.").
			Annotations(entexample.Default(185)),
		field.Uint64("intermediate_direct_from_cpfp_refund_timelock").
			Optional().
			Comment("Timelock value extracted from intermediate_direct_from_cpfp_refund_tx. Generated by hooks.").
			Annotations(entexample.Default(185)),
		field.Bytes("key_tweak").
			Optional().
			Comment("The key tweak scalar applied to the SE's key share to transfer ownership."),
		field.Bytes("sender_key_tweak_proof").
			Optional().
			Comment("Proof from the sender that the key tweak was applied correctly."),
		field.Bytes("receiver_key_tweak").
			Optional().
			Comment("The aggregated key tweak for the receiver to derive their new key."),
		field.UUID("transfer_receiver_id", uuid.UUID{}).
			Optional().
			Nillable().
			Comment("The TransferReceiver this leaf is assigned to."),
		field.UUID("transfer_sender_id", uuid.UUID{}).
			Optional().
			Nillable().
			Comment("The TransferSender this leaf originated from."),
	}
}

// Edges are the edges for the TransferLeaf table.
func (TransferLeaf) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("transfer", Transfer.Type).
			Unique().
			Immutable().
			Required(),
		edge.To("leaf", TreeNode.Type).
			Unique().
			Immutable().
			Required(),
		edge.To("transfer_receiver", TransferReceiver.Type).
			Unique().
			Field("transfer_receiver_id"),
		edge.To("transfer_sender", TransferSender.Type).
			Unique().
			Field("transfer_sender_id"),
	}
}

// Indexes are the indexes for the TransferLeaf table.
func (TransferLeaf) Indexes() []ent.Index {
	return []ent.Index{
		index.Edges("transfer"),
		index.Edges("leaf"),
		index.Fields("update_time", "id").
			StorageKey("transfer_leafs_update_time_id_idx"),

		index.Fields("intermediate_refund_txid").Annotations(
			entsql.IndexWhere("intermediate_refund_txid is not null"),
		),
		index.Fields("intermediate_direct_refund_txid").Annotations(
			entsql.IndexWhere("intermediate_direct_refund_txid is not null"),
		),
		index.Fields("intermediate_direct_from_cpfp_refund_txid").Annotations(
			entsql.IndexWhere("intermediate_direct_from_cpfp_refund_txid is not null"),
		),
		index.Fields("intermediate_refund_timelock").Annotations(
			entsql.IndexWhere("intermediate_refund_timelock is not null"),
		),
		index.Fields("intermediate_direct_refund_timelock").Annotations(
			entsql.IndexWhere("intermediate_direct_refund_timelock is not null"),
		),
		index.Fields("intermediate_direct_from_cpfp_refund_timelock").Annotations(
			entsql.IndexWhere("intermediate_direct_from_cpfp_refund_timelock is not null"),
		),
	}
}

func (TransferLeaf) Hooks() []ent.Hook {
	return []ent.Hook{
		// Validate that the network in the tree matches the network in the transfer
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.TransferLeafFunc(func(ctx context.Context, m *gen.TransferLeafMutation) (ent.Value, error) {
					transferID, transferExists := m.TransferID()
					leafID, leafExists := m.LeafID()

					if !transferExists || !leafExists {
						return nil, fmt.Errorf("transfer leaf mutation must contain transfer ID and leaf ID")
					}

					client := m.Client()

					transfer, err := client.Transfer.Get(ctx, transferID)
					if err != nil {
						return nil, fmt.Errorf("failed to fetch transfer: %w", err)
					}

					leaf, err := client.TreeNode.Get(ctx, leafID)
					if err != nil {
						return nil, fmt.Errorf("failed to fetch leaf: %w", err)
					}

					if transfer.Network != leaf.Network {
						return nil, fmt.Errorf("network mismatch: transfer network %s does not match leaf network %s", transfer.Network, leaf.Network)
					}

					return next.Mutate(ctx, m)
				})
			},
			ent.OpCreate,
		),
		// Define helper hooks that will populate TXIDs for the transactions in the mutation.
		// Clearing a field will also clear a corresponding TXID.
		// Be mindful that updates on transactions are slower because the DB indexes on TXIDs are also updated.
		// The first hook handles single entity updates and the second hook handles creations.
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.TransferLeafFunc(func(ctx context.Context, m *gen.TransferLeafMutation) (ent.Value, error) {
					err := checkTransferLeafTxids(m)
					if err != nil {
						return nil, err
					}

					leafIdUuid, _ := m.ID()
					leafId := leafIdUuid.String()

					// Handling an update on a field
					// intermediate_refund_tx is NotEmpty() so it cannot be cleared, only updated
					if intermediateRefundTxBytes, ok := m.IntermediateRefundTx(); ok {
						intermediateRefundTx, err := common.TxFromRawTxBytes(intermediateRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_refund_tx for transfer leaf %s: %w", leafId, err)
						}
						intermediateRefundTxid := intermediateRefundTx.TxHash()
						m.SetIntermediateRefundTxid(st.NewTxID(intermediateRefundTxid))

						timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_refund_tx timelock for transfer leaf %s: %w", leafId, err)
						}
						m.SetIntermediateRefundTimelock(uint64(timelock))
					}

					if m.IntermediateDirectRefundTxCleared() {
						m.ClearIntermediateDirectRefundTxid()
						m.ClearIntermediateDirectRefundTimelock()
					} else {
						if intermediateDirectRefundTxBytes, ok := m.IntermediateDirectRefundTx(); ok {
							if intermediateDirectRefundTxBytes == nil {
								m.ClearIntermediateDirectRefundTxid()
								m.ClearIntermediateDirectRefundTimelock()
							} else {
								intermediateDirectRefundTx, err := common.TxFromRawTxBytes(intermediateDirectRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx for transfer leaf %s: %w", leafId, err)
								}
								intermediateDirectRefundTxid := intermediateDirectRefundTx.TxHash()
								m.SetIntermediateDirectRefundTxid(st.NewTxID(intermediateDirectRefundTxid))

								timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx timelock for transfer leaf %s: %w", leafId, err)
								}
								m.SetIntermediateDirectRefundTimelock(uint64(timelock))
							}
						}
					}

					if m.IntermediateDirectFromCpfpRefundTxCleared() {
						m.ClearIntermediateDirectFromCpfpRefundTxid()
						m.ClearIntermediateDirectFromCpfpRefundTimelock()
					} else {
						if intermediateDirectFromCpfpRefundTxBytes, ok := m.IntermediateDirectFromCpfpRefundTx(); ok {
							if intermediateDirectFromCpfpRefundTxBytes == nil {
								m.ClearIntermediateDirectFromCpfpRefundTxid()
								m.ClearIntermediateDirectFromCpfpRefundTimelock()
							} else {
								intermediateDirectFromCpfpRefundTx, err := common.TxFromRawTxBytes(intermediateDirectFromCpfpRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx for transfer leaf %s: %w", leafId, err)
								}
								intermediateDirectFromCpfpRefundTxid := intermediateDirectFromCpfpRefundTx.TxHash()
								m.SetIntermediateDirectFromCpfpRefundTxid(st.NewTxID(intermediateDirectFromCpfpRefundTxid))

								timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectFromCpfpRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx timelock for transfer leaf %s: %w", leafId, err)
								}
								m.SetIntermediateDirectFromCpfpRefundTimelock(uint64(timelock))
							}
						}
					}
					return next.Mutate(ctx, m)
				})
			},
			ent.OpUpdateOne|ent.OpUpdate,
		),
		// Create ent hook
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.TransferLeafFunc(func(ctx context.Context, m *gen.TransferLeafMutation) (ent.Value, error) {
					err := checkTransferLeafTxids(m)
					if err != nil {
						return nil, err
					}

					leafIdUuid, _ := m.ID()
					leafId := leafIdUuid.String()

					intermediateRefundTxBytes, _ := m.IntermediateRefundTx()
					intermediateRefundTx, err := common.TxFromRawTxBytes(intermediateRefundTxBytes)
					if err != nil {
						return nil, fmt.Errorf("failed to parse intermediate_refund_tx for transfer leaf %s: %w", leafId, err)
					}
					intermediateRefundTxid := intermediateRefundTx.TxHash()
					m.SetIntermediateRefundTxid(st.NewTxID(intermediateRefundTxid))

					timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateRefundTxBytes)
					if err != nil {
						return nil, fmt.Errorf("failed to parse intermediate_refund_tx timelock for transfer leaf %s: %w", leafId, err)
					}
					m.SetIntermediateRefundTimelock(uint64(timelock))

					intermediateDirectRefundTxBytes, _ := m.IntermediateDirectRefundTx()
					if intermediateDirectRefundTxBytes != nil {
						intermediateDirectRefundTx, err := common.TxFromRawTxBytes(intermediateDirectRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx for transfer leaf %s: %w", leafId, err)
						}
						intermediateDirectRefundTxid := intermediateDirectRefundTx.TxHash()
						m.SetIntermediateDirectRefundTxid(st.NewTxID(intermediateDirectRefundTxid))

						timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx timelock for transfer leaf %s: %w", leafId, err)
						}
						m.SetIntermediateDirectRefundTimelock(uint64(timelock))
					}

					intermediateDirectFromCpfpRefundTxBytes, _ := m.IntermediateDirectFromCpfpRefundTx()
					if intermediateDirectFromCpfpRefundTxBytes != nil {
						intermediateDirectFromCpfpRefundTx, err := common.TxFromRawTxBytes(intermediateDirectFromCpfpRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx for transfer leaf %s: %w", leafId, err)
						}
						intermediateDirectFromCpfpRefundTxid := intermediateDirectFromCpfpRefundTx.TxHash()
						m.SetIntermediateDirectFromCpfpRefundTxid(st.NewTxID(intermediateDirectFromCpfpRefundTxid))

						timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectFromCpfpRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx timelock for transfer leaf %s: %w", leafId, err)
						}
						m.SetIntermediateDirectFromCpfpRefundTimelock(uint64(timelock))
					}
					return next.Mutate(ctx, m)
				})
			},
			ent.OpCreate,
		),
	}
}

// Checks if the txids and timelocks are set directly.
// This is not allowed because the txids and timelocks are generated by hooks from the transactions.
func checkTransferLeafTxids(m *gen.TransferLeafMutation) error {
	if _, ok := m.IntermediateRefundTxid(); ok {
		return fmt.Errorf("intermediate_refund_txid is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectRefundTxid(); ok {
		return fmt.Errorf("intermediate_direct_refund_txid is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectFromCpfpRefundTxid(); ok {
		return fmt.Errorf("intermediate_direct_from_cpfp_refund_txid is not allowed to be set directly")
	}
	if _, ok := m.IntermediateRefundTimelock(); ok {
		return fmt.Errorf("intermediate_refund_timelock is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectRefundTimelock(); ok {
		return fmt.Errorf("intermediate_direct_refund_timelock is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectFromCpfpRefundTimelock(); ok {
		return fmt.Errorf("intermediate_direct_from_cpfp_refund_timelock is not allowed to be set directly")
	}
	return nil
}
