// Code generated by ent, DO NOT EDIT.

package entephemeral

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/entephemeral/predicate"
	"github.com/lightsparkdev/spark/so/entephemeral/signingkeysharesecret"
)

// SigningKeyshareSecretUpdate is the builder for updating SigningKeyshareSecret entities.
type SigningKeyshareSecretUpdate struct {
	config
	hooks     []Hook
	mutation  *SigningKeyshareSecretMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SigningKeyshareSecretUpdate builder.
func (sksu *SigningKeyshareSecretUpdate) Where(ps ...predicate.SigningKeyshareSecret) *SigningKeyshareSecretUpdate {
	sksu.mutation.Where(ps...)
	return sksu
}

// SetUpdateTime sets the "update_time" field.
func (sksu *SigningKeyshareSecretUpdate) SetUpdateTime(t time.Time) *SigningKeyshareSecretUpdate {
	sksu.mutation.SetUpdateTime(t)
	return sksu
}

// SetVersion sets the "version" field.
func (sksu *SigningKeyshareSecretUpdate) SetVersion(i int32) *SigningKeyshareSecretUpdate {
	sksu.mutation.ResetVersion()
	sksu.mutation.SetVersion(i)
	return sksu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (sksu *SigningKeyshareSecretUpdate) SetNillableVersion(i *int32) *SigningKeyshareSecretUpdate {
	if i != nil {
		sksu.SetVersion(*i)
	}
	return sksu
}

// AddVersion adds i to the "version" field.
func (sksu *SigningKeyshareSecretUpdate) AddVersion(i int32) *SigningKeyshareSecretUpdate {
	sksu.mutation.AddVersion(i)
	return sksu
}

// SetSecretShare sets the "secret_share" field.
func (sksu *SigningKeyshareSecretUpdate) SetSecretShare(k keys.Private) *SigningKeyshareSecretUpdate {
	sksu.mutation.SetSecretShare(k)
	return sksu
}

// SetNillableSecretShare sets the "secret_share" field if the given value is not nil.
func (sksu *SigningKeyshareSecretUpdate) SetNillableSecretShare(k *keys.Private) *SigningKeyshareSecretUpdate {
	if k != nil {
		sksu.SetSecretShare(*k)
	}
	return sksu
}

// Mutation returns the SigningKeyshareSecretMutation object of the builder.
func (sksu *SigningKeyshareSecretUpdate) Mutation() *SigningKeyshareSecretMutation {
	return sksu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sksu *SigningKeyshareSecretUpdate) Save(ctx context.Context) (int, error) {
	sksu.defaults()
	return withHooks(ctx, sksu.sqlSave, sksu.mutation, sksu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sksu *SigningKeyshareSecretUpdate) SaveX(ctx context.Context) int {
	affected, err := sksu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sksu *SigningKeyshareSecretUpdate) Exec(ctx context.Context) error {
	_, err := sksu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sksu *SigningKeyshareSecretUpdate) ExecX(ctx context.Context) {
	if err := sksu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sksu *SigningKeyshareSecretUpdate) defaults() {
	if _, ok := sksu.mutation.UpdateTime(); !ok {
		v := signingkeysharesecret.UpdateDefaultUpdateTime()
		sksu.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (sksu *SigningKeyshareSecretUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SigningKeyshareSecretUpdate {
	sksu.modifiers = append(sksu.modifiers, modifiers...)
	return sksu
}

func (sksu *SigningKeyshareSecretUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(signingkeysharesecret.Table, signingkeysharesecret.Columns, sqlgraph.NewFieldSpec(signingkeysharesecret.FieldID, field.TypeUUID))
	if ps := sksu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sksu.mutation.UpdateTime(); ok {
		_spec.SetField(signingkeysharesecret.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := sksu.mutation.Version(); ok {
		_spec.SetField(signingkeysharesecret.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := sksu.mutation.AddedVersion(); ok {
		_spec.AddField(signingkeysharesecret.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := sksu.mutation.SecretShare(); ok {
		_spec.SetField(signingkeysharesecret.FieldSecretShare, field.TypeBytes, value)
	}
	_spec.AddModifiers(sksu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, sksu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingkeysharesecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sksu.mutation.done = true
	return n, nil
}

// SigningKeyshareSecretUpdateOne is the builder for updating a single SigningKeyshareSecret entity.
type SigningKeyshareSecretUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SigningKeyshareSecretMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (sksuo *SigningKeyshareSecretUpdateOne) SetUpdateTime(t time.Time) *SigningKeyshareSecretUpdateOne {
	sksuo.mutation.SetUpdateTime(t)
	return sksuo
}

// SetVersion sets the "version" field.
func (sksuo *SigningKeyshareSecretUpdateOne) SetVersion(i int32) *SigningKeyshareSecretUpdateOne {
	sksuo.mutation.ResetVersion()
	sksuo.mutation.SetVersion(i)
	return sksuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (sksuo *SigningKeyshareSecretUpdateOne) SetNillableVersion(i *int32) *SigningKeyshareSecretUpdateOne {
	if i != nil {
		sksuo.SetVersion(*i)
	}
	return sksuo
}

// AddVersion adds i to the "version" field.
func (sksuo *SigningKeyshareSecretUpdateOne) AddVersion(i int32) *SigningKeyshareSecretUpdateOne {
	sksuo.mutation.AddVersion(i)
	return sksuo
}

// SetSecretShare sets the "secret_share" field.
func (sksuo *SigningKeyshareSecretUpdateOne) SetSecretShare(k keys.Private) *SigningKeyshareSecretUpdateOne {
	sksuo.mutation.SetSecretShare(k)
	return sksuo
}

// SetNillableSecretShare sets the "secret_share" field if the given value is not nil.
func (sksuo *SigningKeyshareSecretUpdateOne) SetNillableSecretShare(k *keys.Private) *SigningKeyshareSecretUpdateOne {
	if k != nil {
		sksuo.SetSecretShare(*k)
	}
	return sksuo
}

// Mutation returns the SigningKeyshareSecretMutation object of the builder.
func (sksuo *SigningKeyshareSecretUpdateOne) Mutation() *SigningKeyshareSecretMutation {
	return sksuo.mutation
}

// Where appends a list predicates to the SigningKeyshareSecretUpdate builder.
func (sksuo *SigningKeyshareSecretUpdateOne) Where(ps ...predicate.SigningKeyshareSecret) *SigningKeyshareSecretUpdateOne {
	sksuo.mutation.Where(ps...)
	return sksuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sksuo *SigningKeyshareSecretUpdateOne) Select(field string, fields ...string) *SigningKeyshareSecretUpdateOne {
	sksuo.fields = append([]string{field}, fields...)
	return sksuo
}

// Save executes the query and returns the updated SigningKeyshareSecret entity.
func (sksuo *SigningKeyshareSecretUpdateOne) Save(ctx context.Context) (*SigningKeyshareSecret, error) {
	sksuo.defaults()
	return withHooks(ctx, sksuo.sqlSave, sksuo.mutation, sksuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sksuo *SigningKeyshareSecretUpdateOne) SaveX(ctx context.Context) *SigningKeyshareSecret {
	node, err := sksuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sksuo *SigningKeyshareSecretUpdateOne) Exec(ctx context.Context) error {
	_, err := sksuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sksuo *SigningKeyshareSecretUpdateOne) ExecX(ctx context.Context) {
	if err := sksuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sksuo *SigningKeyshareSecretUpdateOne) defaults() {
	if _, ok := sksuo.mutation.UpdateTime(); !ok {
		v := signingkeysharesecret.UpdateDefaultUpdateTime()
		sksuo.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (sksuo *SigningKeyshareSecretUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SigningKeyshareSecretUpdateOne {
	sksuo.modifiers = append(sksuo.modifiers, modifiers...)
	return sksuo
}

func (sksuo *SigningKeyshareSecretUpdateOne) sqlSave(ctx context.Context) (_node *SigningKeyshareSecret, err error) {
	_spec := sqlgraph.NewUpdateSpec(signingkeysharesecret.Table, signingkeysharesecret.Columns, sqlgraph.NewFieldSpec(signingkeysharesecret.FieldID, field.TypeUUID))
	id, ok := sksuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entephemeral: missing "SigningKeyshareSecret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sksuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signingkeysharesecret.FieldID)
		for _, f := range fields {
			if !signingkeysharesecret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entephemeral: invalid field %q for query", f)}
			}
			if f != signingkeysharesecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sksuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sksuo.mutation.UpdateTime(); ok {
		_spec.SetField(signingkeysharesecret.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := sksuo.mutation.Version(); ok {
		_spec.SetField(signingkeysharesecret.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := sksuo.mutation.AddedVersion(); ok {
		_spec.AddField(signingkeysharesecret.FieldVersion, field.TypeInt32, value)
	}
	if value, ok := sksuo.mutation.SecretShare(); ok {
		_spec.SetField(signingkeysharesecret.FieldSecretShare, field.TypeBytes, value)
	}
	_spec.AddModifiers(sksuo.modifiers...)
	_node = &SigningKeyshareSecret{config: sksuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sksuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingkeysharesecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sksuo.mutation.done = true
	return _node, nil
}
