// Code generated by ent, DO NOT EDIT.

package partner

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Partner {
	return predicate.Partner(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldUpdateTime, v))
}

// PartnerID applies equality check predicate on the "partner_id" field. It's identical to PartnerIDEQ.
func PartnerID(v string) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldPartnerID, v))
}

// PartnerName applies equality check predicate on the "partner_name" field. It's identical to PartnerNameEQ.
func PartnerName(v string) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldPartnerName, v))
}

// JwtPublicKey applies equality check predicate on the "jwt_public_key" field. It's identical to JwtPublicKeyEQ.
func JwtPublicKey(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldJwtPublicKey, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Partner {
	return predicate.Partner(sql.FieldLTE(FieldUpdateTime, v))
}

// PartnerIDEQ applies the EQ predicate on the "partner_id" field.
func PartnerIDEQ(v string) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldPartnerID, v))
}

// PartnerIDNEQ applies the NEQ predicate on the "partner_id" field.
func PartnerIDNEQ(v string) predicate.Partner {
	return predicate.Partner(sql.FieldNEQ(FieldPartnerID, v))
}

// PartnerIDIn applies the In predicate on the "partner_id" field.
func PartnerIDIn(vs ...string) predicate.Partner {
	return predicate.Partner(sql.FieldIn(FieldPartnerID, vs...))
}

// PartnerIDNotIn applies the NotIn predicate on the "partner_id" field.
func PartnerIDNotIn(vs ...string) predicate.Partner {
	return predicate.Partner(sql.FieldNotIn(FieldPartnerID, vs...))
}

// PartnerIDGT applies the GT predicate on the "partner_id" field.
func PartnerIDGT(v string) predicate.Partner {
	return predicate.Partner(sql.FieldGT(FieldPartnerID, v))
}

// PartnerIDGTE applies the GTE predicate on the "partner_id" field.
func PartnerIDGTE(v string) predicate.Partner {
	return predicate.Partner(sql.FieldGTE(FieldPartnerID, v))
}

// PartnerIDLT applies the LT predicate on the "partner_id" field.
func PartnerIDLT(v string) predicate.Partner {
	return predicate.Partner(sql.FieldLT(FieldPartnerID, v))
}

// PartnerIDLTE applies the LTE predicate on the "partner_id" field.
func PartnerIDLTE(v string) predicate.Partner {
	return predicate.Partner(sql.FieldLTE(FieldPartnerID, v))
}

// PartnerIDContains applies the Contains predicate on the "partner_id" field.
func PartnerIDContains(v string) predicate.Partner {
	return predicate.Partner(sql.FieldContains(FieldPartnerID, v))
}

// PartnerIDHasPrefix applies the HasPrefix predicate on the "partner_id" field.
func PartnerIDHasPrefix(v string) predicate.Partner {
	return predicate.Partner(sql.FieldHasPrefix(FieldPartnerID, v))
}

// PartnerIDHasSuffix applies the HasSuffix predicate on the "partner_id" field.
func PartnerIDHasSuffix(v string) predicate.Partner {
	return predicate.Partner(sql.FieldHasSuffix(FieldPartnerID, v))
}

// PartnerIDEqualFold applies the EqualFold predicate on the "partner_id" field.
func PartnerIDEqualFold(v string) predicate.Partner {
	return predicate.Partner(sql.FieldEqualFold(FieldPartnerID, v))
}

// PartnerIDContainsFold applies the ContainsFold predicate on the "partner_id" field.
func PartnerIDContainsFold(v string) predicate.Partner {
	return predicate.Partner(sql.FieldContainsFold(FieldPartnerID, v))
}

// PartnerNameEQ applies the EQ predicate on the "partner_name" field.
func PartnerNameEQ(v string) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldPartnerName, v))
}

// PartnerNameNEQ applies the NEQ predicate on the "partner_name" field.
func PartnerNameNEQ(v string) predicate.Partner {
	return predicate.Partner(sql.FieldNEQ(FieldPartnerName, v))
}

// PartnerNameIn applies the In predicate on the "partner_name" field.
func PartnerNameIn(vs ...string) predicate.Partner {
	return predicate.Partner(sql.FieldIn(FieldPartnerName, vs...))
}

// PartnerNameNotIn applies the NotIn predicate on the "partner_name" field.
func PartnerNameNotIn(vs ...string) predicate.Partner {
	return predicate.Partner(sql.FieldNotIn(FieldPartnerName, vs...))
}

// PartnerNameGT applies the GT predicate on the "partner_name" field.
func PartnerNameGT(v string) predicate.Partner {
	return predicate.Partner(sql.FieldGT(FieldPartnerName, v))
}

// PartnerNameGTE applies the GTE predicate on the "partner_name" field.
func PartnerNameGTE(v string) predicate.Partner {
	return predicate.Partner(sql.FieldGTE(FieldPartnerName, v))
}

// PartnerNameLT applies the LT predicate on the "partner_name" field.
func PartnerNameLT(v string) predicate.Partner {
	return predicate.Partner(sql.FieldLT(FieldPartnerName, v))
}

// PartnerNameLTE applies the LTE predicate on the "partner_name" field.
func PartnerNameLTE(v string) predicate.Partner {
	return predicate.Partner(sql.FieldLTE(FieldPartnerName, v))
}

// PartnerNameContains applies the Contains predicate on the "partner_name" field.
func PartnerNameContains(v string) predicate.Partner {
	return predicate.Partner(sql.FieldContains(FieldPartnerName, v))
}

// PartnerNameHasPrefix applies the HasPrefix predicate on the "partner_name" field.
func PartnerNameHasPrefix(v string) predicate.Partner {
	return predicate.Partner(sql.FieldHasPrefix(FieldPartnerName, v))
}

// PartnerNameHasSuffix applies the HasSuffix predicate on the "partner_name" field.
func PartnerNameHasSuffix(v string) predicate.Partner {
	return predicate.Partner(sql.FieldHasSuffix(FieldPartnerName, v))
}

// PartnerNameEqualFold applies the EqualFold predicate on the "partner_name" field.
func PartnerNameEqualFold(v string) predicate.Partner {
	return predicate.Partner(sql.FieldEqualFold(FieldPartnerName, v))
}

// PartnerNameContainsFold applies the ContainsFold predicate on the "partner_name" field.
func PartnerNameContainsFold(v string) predicate.Partner {
	return predicate.Partner(sql.FieldContainsFold(FieldPartnerName, v))
}

// JwtPublicKeyEQ applies the EQ predicate on the "jwt_public_key" field.
func JwtPublicKeyEQ(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldEQ(FieldJwtPublicKey, v))
}

// JwtPublicKeyNEQ applies the NEQ predicate on the "jwt_public_key" field.
func JwtPublicKeyNEQ(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldNEQ(FieldJwtPublicKey, v))
}

// JwtPublicKeyIn applies the In predicate on the "jwt_public_key" field.
func JwtPublicKeyIn(vs ...keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldIn(FieldJwtPublicKey, vs...))
}

// JwtPublicKeyNotIn applies the NotIn predicate on the "jwt_public_key" field.
func JwtPublicKeyNotIn(vs ...keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldNotIn(FieldJwtPublicKey, vs...))
}

// JwtPublicKeyGT applies the GT predicate on the "jwt_public_key" field.
func JwtPublicKeyGT(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldGT(FieldJwtPublicKey, v))
}

// JwtPublicKeyGTE applies the GTE predicate on the "jwt_public_key" field.
func JwtPublicKeyGTE(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldGTE(FieldJwtPublicKey, v))
}

// JwtPublicKeyLT applies the LT predicate on the "jwt_public_key" field.
func JwtPublicKeyLT(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldLT(FieldJwtPublicKey, v))
}

// JwtPublicKeyLTE applies the LTE predicate on the "jwt_public_key" field.
func JwtPublicKeyLTE(v keys.JwtPubKey) predicate.Partner {
	return predicate.Partner(sql.FieldLTE(FieldJwtPublicKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Partner) predicate.Partner {
	return predicate.Partner(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Partner) predicate.Partner {
	return predicate.Partner(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Partner) predicate.Partner {
	return predicate.Partner(sql.NotPredicates(p))
}
