// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.33.2
// source: multisig.proto

package multisig

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultisigConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Threshold uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Public keys sorted lexicographically. Order determines canonical hash.
	PublicKeys    [][]byte `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultisigConfig) Reset() {
	*x = MultisigConfig{}
	mi := &file_multisig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultisigConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultisigConfig) ProtoMessage() {}

func (x *MultisigConfig) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultisigConfig.ProtoReflect.Descriptor instead.
func (*MultisigConfig) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{0}
}

func (x *MultisigConfig) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MultisigConfig) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *MultisigConfig) GetPublicKeys() [][]byte {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type KeyedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyedSignature) Reset() {
	*x = KeyedSignature{}
	mi := &file_multisig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedSignature) ProtoMessage() {}

func (x *KeyedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedSignature.ProtoReflect.Descriptor instead.
func (*KeyedSignature) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{1}
}

func (x *KeyedSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *KeyedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MultisigSignatureSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MultisigConfig *MultisigConfig        `protobuf:"bytes,1,opt,name=multisig_config,json=multisigConfig,proto3" json:"multisig_config,omitempty"`
	Signatures     []*KeyedSignature      `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultisigSignatureSet) Reset() {
	*x = MultisigSignatureSet{}
	mi := &file_multisig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultisigSignatureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultisigSignatureSet) ProtoMessage() {}

func (x *MultisigSignatureSet) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultisigSignatureSet.ProtoReflect.Descriptor instead.
func (*MultisigSignatureSet) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{2}
}

func (x *MultisigSignatureSet) GetMultisigConfig() *MultisigConfig {
	if x != nil {
		return x.MultisigConfig
	}
	return nil
}

func (x *MultisigSignatureSet) GetSignatures() []*KeyedSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type SigningAuthority struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Authority:
	//
	//	*SigningAuthority_PublicKey
	//	*SigningAuthority_Multisig
	Authority     isSigningAuthority_Authority `protobuf_oneof:"authority"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningAuthority) Reset() {
	*x = SigningAuthority{}
	mi := &file_multisig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningAuthority) ProtoMessage() {}

func (x *SigningAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningAuthority.ProtoReflect.Descriptor instead.
func (*SigningAuthority) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{3}
}

func (x *SigningAuthority) GetAuthority() isSigningAuthority_Authority {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *SigningAuthority) GetPublicKey() []byte {
	if x != nil {
		if x, ok := x.Authority.(*SigningAuthority_PublicKey); ok {
			return x.PublicKey
		}
	}
	return nil
}

func (x *SigningAuthority) GetMultisig() *MultisigConfig {
	if x != nil {
		if x, ok := x.Authority.(*SigningAuthority_Multisig); ok {
			return x.Multisig
		}
	}
	return nil
}

type isSigningAuthority_Authority interface {
	isSigningAuthority_Authority()
}

type SigningAuthority_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type SigningAuthority_Multisig struct {
	Multisig *MultisigConfig `protobuf:"bytes,2,opt,name=multisig,proto3,oneof"`
}

func (*SigningAuthority_PublicKey) isSigningAuthority_Authority() {}

func (*SigningAuthority_Multisig) isSigningAuthority_Authority() {}

var File_multisig_proto protoreflect.FileDescriptor

var file_multisig_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x25, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x09, 0x74, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x2f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x42, 0x0e, 0xfa, 0x42,
	0x0b, 0x92, 0x01, 0x08, 0x08, 0x02, 0x22, 0x04, 0x7a, 0x02, 0x68, 0x21, 0x52, 0x0a, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x61, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x65,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0a, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x7a, 0x02, 0x68, 0x21, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x27, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x7a, 0x04, 0x10, 0x40, 0x18, 0x49,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x14,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x53, 0x65, 0x74, 0x12, 0x4b, 0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69,
	0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10,
	0x01, 0x52, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67,
	0x2e, 0x4b, 0x65, 0x79, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x10,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x28, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x7a, 0x02, 0x68, 0x21, 0x48, 0x00, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x08, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73,
	0x69, 0x67, 0x42, 0x0b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x64, 0x65, 0x76, 0x2f, 0x73, 0x70, 0x61, 0x72,
	0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_multisig_proto_rawDescOnce sync.Once
	file_multisig_proto_rawDescData []byte
)

func file_multisig_proto_rawDescGZIP() []byte {
	file_multisig_proto_rawDescOnce.Do(func() {
		file_multisig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multisig_proto_rawDesc), len(file_multisig_proto_rawDesc)))
	})
	return file_multisig_proto_rawDescData
}

var file_multisig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_multisig_proto_goTypes = []any{
	(*MultisigConfig)(nil),       // 0: multisig.MultisigConfig
	(*KeyedSignature)(nil),       // 1: multisig.KeyedSignature
	(*MultisigSignatureSet)(nil), // 2: multisig.MultisigSignatureSet
	(*SigningAuthority)(nil),     // 3: multisig.SigningAuthority
}
var file_multisig_proto_depIdxs = []int32{
	0, // 0: multisig.MultisigSignatureSet.multisig_config:type_name -> multisig.MultisigConfig
	1, // 1: multisig.MultisigSignatureSet.signatures:type_name -> multisig.KeyedSignature
	0, // 2: multisig.SigningAuthority.multisig:type_name -> multisig.MultisigConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_multisig_proto_init() }
func file_multisig_proto_init() {
	if File_multisig_proto != nil {
		return
	}
	file_multisig_proto_msgTypes[3].OneofWrappers = []any{
		(*SigningAuthority_PublicKey)(nil),
		(*SigningAuthority_Multisig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multisig_proto_rawDesc), len(file_multisig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multisig_proto_goTypes,
		DependencyIndexes: file_multisig_proto_depIdxs,
		MessageInfos:      file_multisig_proto_msgTypes,
	}.Build()
	File_multisig_proto = out.File
	file_multisig_proto_goTypes = nil
	file_multisig_proto_depIdxs = nil
}
