// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: multisig.proto

package multisig

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MultisigConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MultisigConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MultisigConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MultisigConfigMultiError,
// or nil if none found.
func (m *MultisigConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *MultisigConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Version

	if m.GetThreshold() < 1 {
		err := MultisigConfigValidationError{
			field:  "Threshold",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetPublicKeys()) < 2 {
		err := MultisigConfigValidationError{
			field:  "PublicKeys",
			reason: "value must contain at least 2 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetPublicKeys() {
		_, _ = idx, item

		if len(item) != 33 {
			err := MultisigConfigValidationError{
				field:  fmt.Sprintf("PublicKeys[%v]", idx),
				reason: "value length must be 33 bytes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return MultisigConfigMultiError(errors)
	}

	return nil
}

// MultisigConfigMultiError is an error wrapping multiple validation errors
// returned by MultisigConfig.ValidateAll() if the designated constraints
// aren't met.
type MultisigConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MultisigConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MultisigConfigMultiError) AllErrors() []error { return m }

// MultisigConfigValidationError is the validation error returned by
// MultisigConfig.Validate if the designated constraints aren't met.
type MultisigConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MultisigConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MultisigConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MultisigConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MultisigConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MultisigConfigValidationError) ErrorName() string { return "MultisigConfigValidationError" }

// Error satisfies the builtin error interface
func (e MultisigConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMultisigConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MultisigConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MultisigConfigValidationError{}

// Validate checks the field values on KeyedSignature with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KeyedSignature) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KeyedSignature with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KeyedSignatureMultiError,
// or nil if none found.
func (m *KeyedSignature) ValidateAll() error {
	return m.validate(true)
}

func (m *KeyedSignature) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetPublicKey()) != 33 {
		err := KeyedSignatureValidationError{
			field:  "PublicKey",
			reason: "value length must be 33 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := len(m.GetSignature()); l < 64 || l > 73 {
		err := KeyedSignatureValidationError{
			field:  "Signature",
			reason: "value length must be between 64 and 73 bytes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return KeyedSignatureMultiError(errors)
	}

	return nil
}

// KeyedSignatureMultiError is an error wrapping multiple validation errors
// returned by KeyedSignature.ValidateAll() if the designated constraints
// aren't met.
type KeyedSignatureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KeyedSignatureMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KeyedSignatureMultiError) AllErrors() []error { return m }

// KeyedSignatureValidationError is the validation error returned by
// KeyedSignature.Validate if the designated constraints aren't met.
type KeyedSignatureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KeyedSignatureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KeyedSignatureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KeyedSignatureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KeyedSignatureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KeyedSignatureValidationError) ErrorName() string { return "KeyedSignatureValidationError" }

// Error satisfies the builtin error interface
func (e KeyedSignatureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKeyedSignature.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KeyedSignatureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KeyedSignatureValidationError{}

// Validate checks the field values on MultisigSignatureSet with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MultisigSignatureSet) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MultisigSignatureSet with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MultisigSignatureSetMultiError, or nil if none found.
func (m *MultisigSignatureSet) ValidateAll() error {
	return m.validate(true)
}

func (m *MultisigSignatureSet) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetMultisigConfig() == nil {
		err := MultisigSignatureSetValidationError{
			field:  "MultisigConfig",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetMultisigConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MultisigSignatureSetValidationError{
					field:  "MultisigConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MultisigSignatureSetValidationError{
					field:  "MultisigConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMultisigConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MultisigSignatureSetValidationError{
				field:  "MultisigConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetSignatures() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MultisigSignatureSetValidationError{
						field:  fmt.Sprintf("Signatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MultisigSignatureSetValidationError{
						field:  fmt.Sprintf("Signatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MultisigSignatureSetValidationError{
					field:  fmt.Sprintf("Signatures[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MultisigSignatureSetMultiError(errors)
	}

	return nil
}

// MultisigSignatureSetMultiError is an error wrapping multiple validation
// errors returned by MultisigSignatureSet.ValidateAll() if the designated
// constraints aren't met.
type MultisigSignatureSetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MultisigSignatureSetMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MultisigSignatureSetMultiError) AllErrors() []error { return m }

// MultisigSignatureSetValidationError is the validation error returned by
// MultisigSignatureSet.Validate if the designated constraints aren't met.
type MultisigSignatureSetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MultisigSignatureSetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MultisigSignatureSetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MultisigSignatureSetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MultisigSignatureSetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MultisigSignatureSetValidationError) ErrorName() string {
	return "MultisigSignatureSetValidationError"
}

// Error satisfies the builtin error interface
func (e MultisigSignatureSetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMultisigSignatureSet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MultisigSignatureSetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MultisigSignatureSetValidationError{}

// Validate checks the field values on SigningAuthority with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SigningAuthority) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SigningAuthority with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SigningAuthorityMultiError, or nil if none found.
func (m *SigningAuthority) ValidateAll() error {
	return m.validate(true)
}

func (m *SigningAuthority) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Authority.(type) {
	case *SigningAuthority_PublicKey:
		if v == nil {
			err := SigningAuthorityValidationError{
				field:  "Authority",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if len(m.GetPublicKey()) != 33 {
			err := SigningAuthorityValidationError{
				field:  "PublicKey",
				reason: "value length must be 33 bytes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	case *SigningAuthority_Multisig:
		if v == nil {
			err := SigningAuthorityValidationError{
				field:  "Authority",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetMultisig()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SigningAuthorityValidationError{
						field:  "Multisig",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SigningAuthorityValidationError{
						field:  "Multisig",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMultisig()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SigningAuthorityValidationError{
					field:  "Multisig",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return SigningAuthorityMultiError(errors)
	}

	return nil
}

// SigningAuthorityMultiError is an error wrapping multiple validation errors
// returned by SigningAuthority.ValidateAll() if the designated constraints
// aren't met.
type SigningAuthorityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SigningAuthorityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SigningAuthorityMultiError) AllErrors() []error { return m }

// SigningAuthorityValidationError is the validation error returned by
// SigningAuthority.Validate if the designated constraints aren't met.
type SigningAuthorityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SigningAuthorityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SigningAuthorityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SigningAuthorityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SigningAuthorityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SigningAuthorityValidationError) ErrorName() string { return "SigningAuthorityValidationError" }

// Error satisfies the builtin error interface
func (e SigningAuthorityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSigningAuthority.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SigningAuthorityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SigningAuthorityValidationError{}
