// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: multisig.proto

package multisig

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultisigConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Threshold uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Public keys sorted lexicographically. Order determines canonical hash.
	PublicKeys    [][]byte `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultisigConfig) Reset() {
	*x = MultisigConfig{}
	mi := &file_multisig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultisigConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultisigConfig) ProtoMessage() {}

func (x *MultisigConfig) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultisigConfig.ProtoReflect.Descriptor instead.
func (*MultisigConfig) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{0}
}

func (x *MultisigConfig) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MultisigConfig) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *MultisigConfig) GetPublicKeys() [][]byte {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type KeyedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyedSignature) Reset() {
	*x = KeyedSignature{}
	mi := &file_multisig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedSignature) ProtoMessage() {}

func (x *KeyedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedSignature.ProtoReflect.Descriptor instead.
func (*KeyedSignature) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{1}
}

func (x *KeyedSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *KeyedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MultisigSignatureSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MultisigConfig *MultisigConfig        `protobuf:"bytes,1,opt,name=multisig_config,json=multisigConfig,proto3" json:"multisig_config,omitempty"`
	Signatures     []*KeyedSignature      `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultisigSignatureSet) Reset() {
	*x = MultisigSignatureSet{}
	mi := &file_multisig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultisigSignatureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultisigSignatureSet) ProtoMessage() {}

func (x *MultisigSignatureSet) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultisigSignatureSet.ProtoReflect.Descriptor instead.
func (*MultisigSignatureSet) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{2}
}

func (x *MultisigSignatureSet) GetMultisigConfig() *MultisigConfig {
	if x != nil {
		return x.MultisigConfig
	}
	return nil
}

func (x *MultisigSignatureSet) GetSignatures() []*KeyedSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type SigningAuthority struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Authority:
	//
	//	*SigningAuthority_PublicKey
	//	*SigningAuthority_Multisig
	Authority     isSigningAuthority_Authority `protobuf_oneof:"authority"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningAuthority) Reset() {
	*x = SigningAuthority{}
	mi := &file_multisig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningAuthority) ProtoMessage() {}

func (x *SigningAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_multisig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningAuthority.ProtoReflect.Descriptor instead.
func (*SigningAuthority) Descriptor() ([]byte, []int) {
	return file_multisig_proto_rawDescGZIP(), []int{3}
}

func (x *SigningAuthority) GetAuthority() isSigningAuthority_Authority {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *SigningAuthority) GetPublicKey() []byte {
	if x != nil {
		if x, ok := x.Authority.(*SigningAuthority_PublicKey); ok {
			return x.PublicKey
		}
	}
	return nil
}

func (x *SigningAuthority) GetMultisig() *MultisigConfig {
	if x != nil {
		if x, ok := x.Authority.(*SigningAuthority_Multisig); ok {
			return x.Multisig
		}
	}
	return nil
}

type isSigningAuthority_Authority interface {
	isSigningAuthority_Authority()
}

type SigningAuthority_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type SigningAuthority_Multisig struct {
	Multisig *MultisigConfig `protobuf:"bytes,2,opt,name=multisig,proto3,oneof"`
}

func (*SigningAuthority_PublicKey) isSigningAuthority_Authority() {}

func (*SigningAuthority_Multisig) isSigningAuthority_Authority() {}

var File_multisig_proto protoreflect.FileDescriptor

const file_multisig_proto_rawDesc = "" +
	"\n" +
	"\x0emultisig.proto\x12\bmultisig\x1a\x17validate/validate.proto\"\x82\x01\n" +
	"\x0eMultisigConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12%\n" +
	"\tthreshold\x18\x02 \x01(\rB\a\xfaB\x04*\x02(\x01R\tthreshold\x12/\n" +
	"\vpublic_keys\x18\x03 \x03(\fB\x0e\xfaB\v\x92\x01\b\b\x02\"\x04z\x02h!R\n" +
	"publicKeys\"a\n" +
	"\x0eKeyedSignature\x12&\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fB\a\xfaB\x04z\x02h!R\tpublicKey\x12'\n" +
	"\tsignature\x18\x02 \x01(\fB\t\xfaB\x06z\x04\x10@\x18IR\tsignature\"\x9d\x01\n" +
	"\x14MultisigSignatureSet\x12K\n" +
	"\x0fmultisig_config\x18\x01 \x01(\v2\x18.multisig.MultisigConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x0emultisigConfig\x128\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2\x18.multisig.KeyedSignatureR\n" +
	"signatures\"\x81\x01\n" +
	"\x10SigningAuthority\x12(\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fB\a\xfaB\x04z\x02h!H\x00R\tpublicKey\x126\n" +
	"\bmultisig\x18\x02 \x01(\v2\x18.multisig.MultisigConfigH\x00R\bmultisigB\v\n" +
	"\tauthorityB/Z-github.com/lightsparkdev/spark/proto/multisigb\x06proto3"

var (
	file_multisig_proto_rawDescOnce sync.Once
	file_multisig_proto_rawDescData []byte
)

func file_multisig_proto_rawDescGZIP() []byte {
	file_multisig_proto_rawDescOnce.Do(func() {
		file_multisig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multisig_proto_rawDesc), len(file_multisig_proto_rawDesc)))
	})
	return file_multisig_proto_rawDescData
}

var file_multisig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_multisig_proto_goTypes = []any{
	(*MultisigConfig)(nil),       // 0: multisig.MultisigConfig
	(*KeyedSignature)(nil),       // 1: multisig.KeyedSignature
	(*MultisigSignatureSet)(nil), // 2: multisig.MultisigSignatureSet
	(*SigningAuthority)(nil),     // 3: multisig.SigningAuthority
}
var file_multisig_proto_depIdxs = []int32{
	0, // 0: multisig.MultisigSignatureSet.multisig_config:type_name -> multisig.MultisigConfig
	1, // 1: multisig.MultisigSignatureSet.signatures:type_name -> multisig.KeyedSignature
	0, // 2: multisig.SigningAuthority.multisig:type_name -> multisig.MultisigConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_multisig_proto_init() }
func file_multisig_proto_init() {
	if File_multisig_proto != nil {
		return
	}
	file_multisig_proto_msgTypes[3].OneofWrappers = []any{
		(*SigningAuthority_PublicKey)(nil),
		(*SigningAuthority_Multisig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multisig_proto_rawDesc), len(file_multisig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multisig_proto_goTypes,
		DependencyIndexes: file_multisig_proto_depIdxs,
		MessageInfos:      file_multisig_proto_msgTypes,
	}.Build()
	File_multisig_proto = out.File
	file_multisig_proto_goTypes = nil
	file_multisig_proto_depIdxs = nil
}
